(function(g){var window=this;var s4=function(a){var b={format:a.B,languageCode:a.A,languageName:a.D,displayName:g.RH(a),kind:a.C,name:a.F,id:a.Ja,is_servable:a.N,is_default:a.isDefault,is_translateable:a.H,vss_id:a.G};a.o&&(a=a.o,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.o,id:a.id,is_default:a.isDefault});return b},t4=function(a){return a.o?a.o.languageCode:a.A},pBa=function(a,b){var c=new g.QH;
c.A=a.A;c.D=a.D;c.F=a.F;c.C=a.C;c.isDefault=!1;c.H=a.H;c.G=a.G;c.J=a.J;c.o=b;return c},u4=function(a){return(a=g.cU(a.app,void 0))?a.G?a.G.C:0:0},v4=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.vQ.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.D=f;this.A=k},w4=function(a,b,c,d,e){g.vQ.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.A=[]},y4=function(a){a=void 0===a?{}:a;
var b="_"+x4++;return new w4(0,0x8000000000000,0,b,a)},z4=function(a,b,c,d,e,f){var k={};
g.Ea(k,b);g.Ea(k,a.params);g.Ea(k,c);var l={};g.Ea(l,b.ob);a.params.ob&&g.Ea(l,a.params.ob);g.Ea(l,c.ob);k.ob=l;g.W.call(this,{I:"div",M:"caption-window",U:{id:"caption-window-"+a.id,dir:1==k.Bl?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},O:[{I:"span",M:"captions-text"}]});this.D=[];this.N=!1;this.H=a;this.G=[];this.J=[];this.Ca=e;this.za=f;this.F=null;this.ca=.96*e;this.ma=.96*f;this.B=k;this.wa=c;this.C=this.o["captions-text"];this.pa=null!=this.C.style["box-decoration-break"]||
null!=this.C.style["-webkit-box-decoration-break"];this.P=d/360*16;this.type=0;this.ha=this.P*qBa(l);a=new g.MF(this.element,!0);g.N(this,a);a.subscribe("dragstart",this.AQ,this);a.subscribe("dragmove",this.zQ,this);a.subscribe("dragend",this.yQ,this);this.ka=this.ia=0;a="";this.B.windowOpacity&&(a=g.Ht(this.B.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.B.windowOpacity+")");b={"background-color":a,display:!1===this.B.isVisible?"none":"","text-align":rBa[this.B.textAlign]};this.pa&&(b["border-radius"]=
a?this.ha/8+"px":"");g.wh(this.element,b);switch(this.B.Jg){case 0:case 1:case 2:g.T(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.T(this.element,"ytp-caption-window-bottom")}},qBa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},A4=function(a,b){var c={},d=b.background?b.background:a.B.ob.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.B.ob.backgroundOpacity;d=g.Ht(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.pa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ha/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.P*qBa(b)+"px";d=1;e=b.color||a.B.ob.color;if(b.color||null!=b.textOpacity)e=g.Ht(e),d=null==b.textOpacity?a.B.ob.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Fz&&(k=e=b.Fz);var l=a.P/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),t=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=t;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.AE()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.B.ob.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Ff&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.gu&&(c.visibility="hidden");return c},sBa=function(a,b,c){a.N=a.N||!!c;
var d={};g.Ea(d,a.B.ob);g.Ea(d,c||b.A);g.Ea(d,a.wa.ob);c=a.G[0];if(c&&d.background==c.background&&d.backgroundOpacity==c.backgroundOpacity&&!!d.gu==!!c.gu&&d.charEdgeStyle==c.charEdgeStyle){var e;for(e=0;e<a.G.length;e++)if(g.bc(d,a.G[e])){var f=a.J[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.Nd("SPAN");g.wh(f,A4(a,e));a.J[0].appendChild(f);e=1}a.J.length=e;a.G.length=e}else a.J.length=0,a.G.length=0,f=g.Nd("SPAN"),g.wh(f,A4(a,d)),a.C.appendChild(f);a.F&&a.F.parentNode!=f&&(g.Td(a.F),
f.appendChild(a.F));c=(k=g.v(b.text))?b.text.split("\n"):[b.text];for(e=0;e<c.length;e++){var l=c[e];if(0<e||0==a.D.length||!b.D){if(0<e||0!=a.D.length){var m=g.Nd("BR");f.appendChild(m)}f.appendChild(g.Od("\u00a0"));a.F=g.Od("\u00a0");f.appendChild(a.F)}l&&(l=k?g.Od(l):l,m=a.F,m.parentNode&&m.parentNode.insertBefore(l,m))}a.G.push(d);a.J.push(f);a.D.push(b)},tBa=function(){},C4=function(){this.C=this.A=this.mode=this.B=0;
this.D=new B4(this);this.F=new B4(this);this.o=[];this.clear()},vBa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Bo:a,
Co:b,result:0};a=uBa[a];b=uBa[b];if(a&128){if(!(b&128)&&0!=c.o&&c.A==b)return{Bo:a,Co:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Bo:a,Co:b,result:2};return{Bo:a,Co:b,result:3}},xBa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.C&&a.reset(),a.D.o.clear(),a.F.o.clear()):(a.C=0,wBa(a.D,b,c,d))},yBa=function(a,b){a.o.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.o.length;c++){var d=a.o[c];a.A=d.time;0==d.type?xBa(a,d.Az,d.Bz,b):1==d.type&&a.B&496&&wBa(a.F,d.Az,d.Bz,b)}a.o.length=0},D4=function(){this.o=0},E4=function(){this.A=this.B=this.o=0},F4=function(){this.timestamp=this.Pe=0},G4=function(a){this.B=[];
for(var b=0;15>=b;b++){this.B[b]=[];for(var c=0;32>=c;c++)this.B[b][c]=new F4}this.o=this.A=this.row=0;this.style=new D4;this.D=a;this.C=0},H4=function(a,b){if(3==a.style.o){for(var c=0,d=0,e=a.D.A+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var t=a.B[m][p];
if(0!=t.Pe){0==c&&(c=m,d=p);n=String.fromCharCode(t.Pe);var w=t.timestamp;w<e&&(e=w);t.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==t.Pe||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.A+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.B[k][m],t=p.Pe,0!=t&&(0==c&&(c=k,d=m),n=String.fromCharCode(t),w=p.timestamp,w<=e&&(e=w),l+=n,p.reset()),32==m||0==t)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},DBa=function(a,b){switch(a){case 0:return zBa[(b&127)-32];
case 1:return ABa[b&15];case 2:return BBa[b&31];case 3:return CBa[b&31]}return 0},I4=function(a){return a.B[a.row][a.A]},J4=function(a,b,c){2<=b&&1<a.A&&(--a.A,I4(a).Pe=0);
var d=I4(a);d.timestamp=a.D.A+0;d.Pe=DBa(b,c);32>a.A&&a.A++},EBa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.B[b+e][f].So(a.B[c+e][f])},K4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},L4=function(a){a.row=0<a.o?a.o:1;
a.A=1;K4(a,0,15)},M4=function(a){this.C=a;
this.D=0;this.style=new D4;this.F=new G4(a);this.G=new G4(a);this.H=new G4(a);this.A=this.F;this.B=this.G;this.o=this.A},N4=function(a,b,c){var d=a.A,e=!1;
switch(a.style.get()){case 4:if(0<d.o)break;case 1:case 2:H4(d,c),L4(a.A),L4(a.B),d.row=15,d.o=b,e=!0}a.style.set(3);a.o=d;a.o.style=a.style;a.C.mode=1<<d.C;e?d.A=1:d.o!=b&&(d.o>b?(H4(d,c),K4(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},FBa=function(a){a.style.set(1);
a.o=a.B;a.o.o=0;a.o.style=a.style;a.C.mode=1<<a.o.C},GBa=function(a){a.style.set(4);
a.o=a.H;a.o.style=a.style;a.C.mode=1<<a.o.C},B4=function(a){this.A=a;
this.o=new E4;this.D=0;this.B=new M4(a);this.F=new M4(a);this.C=this.B},wBa=function(a,b,c,d){a.o.update();
b=vBa(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Bo;c=b.Co;if(32<=e||!e)a.A.mode&a.A.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.o,b&96&&J4(a,0,b),c&96&&J4(a,0,c),0!=b&&0!=c&&3==a.style.o&&H4(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.B=e,b.A=c,b.o=2,b=e&8?a.F:a.B,a.C=b,a.A.mode=1<<(a.D<<2)+(b.D<<1)+(4==b.style.o?1:0),(a.A.mode|1<<(a.D<<2)+(b.D<<1)+(4!=b.style.o?1:0))&a.A.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.o&&(d=c.o,d==c.row))break;var f=1+c.row-c.o,k=1+d-c.o;EBa(c,k,f,c.o);b=f;e=c.o;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));K4(c,b,e)}}c.row=d;c.A=a+1}else switch(e&7){case 1:switch(c&112){case 32:J4(b.o,0,32);break a;case 48:57==c?(b=b.o,I4(b).Pe=0,32>b.A&&b.A++):J4(b.o,1,c&15)}break;case 2:c&32&&J4(b.o,2,c&31);break;case 3:c&32&&J4(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:FBa(b);break;
case 33:b=b.o;1<b.A&&(--b.A,I4(b).Pe=0);break;case 36:b=b.o;d=I4(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.B[a][c]==d){for(;32>=c;c++)b.B[a][c].reset();break}break;case 37:N4(b,2,d);break;case 38:N4(b,3,d);break;case 39:N4(b,4,d);break;case 40:J4(b.o,0,32);break;case 41:b.style.set(2);b.o=b.A;b.o.o=0;b.o.style=b.style;b.C.mode=1<<b.o.C;break;case 42:d=b.H;d.o=15;d.style.set(4);L4(d);GBa(b);break;case 43:GBa(b);break;case 44:a=b.A;switch(b.style.get()){case 1:case 2:case 3:H4(a,d)}K4(a,0,15);break;
case 45:b:{a=b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.A=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;H4(a,d);EBa(a,b,b+1,a.o-1);K4(a,a.row,1)}break;case 46:K4(b.B,0,15);break;case 47:H4(b.A,d);d=b.B;a=b.C.A+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.B[c][e].timestamp=a;d=b.B;b.B=b.A;b.A=d;FBa(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.o,32<(b.A+=c&3)&&(b.A=32)}}},O4=function(a){g.M.apply(this,arguments)},P4=function(a){O4.call(this);
this.A=a;this.o=null},IBa=function(a,b,c){var d=a.getAttribute("t");
d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0);var e=a.getAttribute("d");e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.is("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");HBa(d,e,k,b,f,a.firstChild,{},c)},HBa=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.Ff=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");Q4.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new v4(a,b,c,d,n.nodeValue,e||0<m,g.Yb(k)?void 0:k));else{var p={};g.Ea(p,k);HBa(a,b,c,d,e||0<m,n,p,l)}}},R4=function(){O4.call(this);
this.A={};this.o=null},S4=function(a){O4.call(this);
this.C={};this.J={};this.K={};this.D="_"+x4++;this.F=a;this.H={};this.A=this.o=null;this.G=!0},T4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},U4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},V4=function(a,b){var c=T4(a,b);
if(void 0!=c)return c},W4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Q4.test(c),c},JBa=function(a,b){var c={},d=b.getAttribute("ws");
g.Ea(c,d?a.K[d]:a.F);d=V4(b,"mh");null!=d&&(c.bv=d);d=V4(b,"ju");null!=d&&(c.textAlign=d);d=V4(b,"pd");null!=d&&(c.Bl=d);d=W4(b,"wfc");null!=d&&(c.windowColor=d);d=T4(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},KBa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ea(c,a.J[d]);d=V4(b,"ap");null!=d&&(c.Jg=d);d=T4(b,"cc");null!=d&&(c.Zs=d);d=T4(b,"ah");null!=d&&(c.Gf=d);d=T4(b,"rc");null!=d&&(c.ar=d);d=T4(b,"av");null!=d&&(c.sh=d);return c},LBa=function(a,b,c,d){var e={};
g.Ea(e,KBa(a,b));g.Ea(e,JBa(a,b));d?g.bc(e,a.F)?(d=a.D,e=a.F):d="_"+x4++:d=b.getAttribute("id")||"_"+x4++;a=T4(b,"t")+c;b=T4(b,"d")||0x8000000000000;return new w4(a,b,0,d,e)},X4=function(a,b,c){this.G=c;
this.version=this.F=this.C=this.o=0;this.A=new window.DataView(a);this.B=[]},Y4=function(a){var b=a.o;
a.o+=1;return a.A.getUint8(b)},Z4=function(a){var b=a.o;
a.o+=4;return a.A.getUint32(b)},$4=function(a,b){O4.call(this);
this.A=a;this.track="CC3"==b.D?4:0;this.o=new C4;this.o.B=1<<this.track},NBa=function(a){if(g.v(a))return!1;
a=new X4(a,8,0);return MBa(a)},MBa=function(a){if(!(a.o<a.A.byteLength)||1380139777!=Z4(a))return!1;
a.version=Y4(a);if(1<a.version)return!1;Y4(a);Y4(a);Y4(a);return!0},OBa=function(){this.A=[];
this.o=[]},a5=function(a,b){return b?a.o.concat(a.A):a.o},b5=function(a,b){switch(b.C){case "asr":var c=a.A;
g.Ia(c,(0,g.B)(b.K,b))||c.push(b);break;default:c=a.o,g.Ia(c,(0,g.B)(b.K,b))||c.push(b)}},c5=function(){O4.call(this)},PBa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Ff=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType){p=new v4(b,c,d,e.id,p.nodeValue,f||0<n,g.Yb(l)?void 0:l);m.push(p);var t=e;g.N(t,p);t.A.push(p)}else t={},g.Ea(t,l),PBa(a,b,c,d,e,!0,p,t,m)}},d5=function(a){var b=0;
a=g.q(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+(0,window.parseFloat)(c.value);return 1E3*b},QBa=function(a,b,c,d){d=Object.assign({bv:0},d);
return new w4(a,b,c,"_"+x4++,d)},e5=function(a){g.M.call(this);
this.CB=!!a;this.A=new OBa;this.F=[];this.o=null},SBa=function(a){var b={};
if(a=t4(a))b.lang=a,RBa.test(a)&&(b.Bl=1);return b},TBa=function(a,b,c,d,e){d=d||0;
e=e||0;if(!g.v(b)){var f=new window.DataView(b);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.GJ(f,1835295092),b=b.slice(f.dataOffset,f.dataOffset+f.size),!NBa(b)&&(b=g.ne(new window.Uint8Array(b)),!b)))return[]}if(g.v(b)){if("WEBVTT"==b.substring(0,6))return a.o||(a.o=new c5),.01>Math.random()&&g.XD(Error("Deprecated subtitles format in web player: WebVTT")),a.o.B(b,d);b=g.is(b);if(!b||!b.firstChild)return[];if(!a.o)if("timedtext"==b.firstChild.tagName)3==(0,window.parseInt)(b.firstChild.getAttribute("format"),
10)?a.o=new S4(SBa(c)):(a.o=new R4,.01>Math.random()&&g.XD(Error("Deprecated subtitles format in web player: Format2"))),g.N(a,a.o);else try{a.o=new P4(SBa(c));g.N(a,a.o);var k=a.o.B(b,d);.01>Math.random()&&g.XD(Error("Deprecated subtitles format in web player: Format1"));return k}catch(l){return g.VD(l),a.o=null,[]}return a.o.B(b,d)}try{if(NBa(b))return a.o||(a.o=new $4(e,c)),a.o.B(b,d)}catch(l){g.VD(l),a.o=null}return[]},f5=function(a){e5.call(this,a.Io);
this.C=void 0;this.B=null;this.F=a.captionTranslationLanguages},g5=function(){this.wb=[]},h5=function(a,b,c,d,e,f){g.M.call(this);
this.L=a;this.B=b;this.F=new g5;this.o=null;this.J=d;this.N=f;this.A=this.C=null;this.H=c;this.G=e||!1;this.K=new g.V(this.WB,1E3,this);g.N(this,this.K);this.D=new g.HF(this);g.N(this,this.D);this.D.R(b,"seekto",this.dD);this.dD(b.getCurrentTime());this.WB()},UBa=function(a,b){b-=u4(a.B);
var c=a.o;a.o=g.Ga(a.H.Ug(b).o);c!=a.o&&a.N&&a.N()},VBa=function(a,b){var c=g.dL(b,a.L,{}).Xa(),d={format:"RAW",
withCredentials:!0};a.G&&(d.responseType="arraybuffer");a.A=g.OE(c,d,3,100).then((0,g.B)(a.kV,a));a.C=b;c=a.F;d=a.C.o[0].Aa;var e=g.bb(c.wb,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.wb[e-1]&&e<c.wb.length&&1==c.wb[e]-d?(g.Qa(c.wb,e),g.Qa(c.wb,e-1)):0<e&&1==d-c.wb[e-1]?c.wb[e-1]=d:e<c.wb.length&&1==c.wb[e]-d?c.wb[e]=d:(g.Ya(c.wb,e,0,d),g.Ya(c.wb,e+1,0,d)))},i5=function(a,b){e5.call(this);
this.B=a;this.T=b;this.C=null;this.D=!1;this.G=g.RM(g.Y(this.T))},WBa=function(a,b){if(b in a.B.o)return a.B.o[b];
if(g.DL(a.B))for(var c in a.B.o){var d=a.B.o[c];if(g.gI(d.info.mimeType))return d}return null},XBa=function(a,b){return a.Kk()&&null!=a.sa||g.RM(g.Y(b))&&null!=a.sa&&null!=a.sa.o.rawcc},j5=function(a,b,c,d,e,f){z4.call(this,a,b,c,d,e,f);
this.type=1},k5=function(a,b,c,d,e,f){z4.call(this,a,b,c,d,e,f);
g.T(this.element,"ytp-caption-window-rollup");this.type=2;this.L=this.Y=0;this.aa=this.K=window.NaN;this.ua=null;this.ga=new g.V(this.pV,433,this);g.N(this,this.ga)},l5=function(a){if(!a.Y){var b=g.Nd("SPAN");
g.wh(b,A4(a,a.B.ob));a.C.appendChild(b);b.appendChild(g.Od("M"));var c=b.offsetHeight,d=g.Nd("BR");b.appendChild(d);b.appendChild(g.Od("M"));a.Y=b.offsetHeight-c;a.C.removeChild(b)}return a.Y},YBa=function(a){if((0,window.isNaN)(a.K)){var b=a.B.Zs;
if(b){var c=g.Nd("SPAN");g.be(c,"\u2013".repeat(b));g.wh(c,A4(a,a.B.ob));a.C.appendChild(c);a.K=c.offsetWidth;a.C.removeChild(c)}else a.K=0}return a.K},m5=function(a,b,c,d){e5.call(this,d);
c=c||g.hE(a).hl||"";c=c.split("_").join("-");this.D=g.jE(a,{hl:c});this.C=b;this.G={};this.B=null},p5=function(a){g.DU.call(this,a);
this.C=g.Y(a);this.A=a.getVideoData();this.ka=g.$T(a);this.T=a;var b=null,c=g.zD("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.iD(c));this.aa=b;this.D={ob:{}};this.G={ob:{}};this.L=[];this.N={};this.Y={};this.K=!1;this.ma="1"==this.A.uc.cc_auto_caps||"1"==this.C.Rb.cc_auto_caps;b="3"==this.C.C&&!!g.uU(a)&&g.uU(a).Vn();this.F=(c=!this.C.experiments.o("web_player_native_controls_live_captions_fix_killswitch"))?b&&!this.A.Ka:b;this.ga=c&&b&&this.A.Ka&&XBa(this.A,this.T);c=b=this.o=this.B=
this.H=this.J=this.P=this.ia=null;this.F||(b=new g.ju(this.HG,void 0,this),g.N(this,b),c=new g.V(this.VW,2E3,this),g.N(this,c));this.ba=b;this.ca=c;this.Z=new g.HF(this);g.N(this,this.Z);this.F||this.Z.R(a,"resize",this.vx);this.Z.R(a,"onPlaybackAudioChange",this.iS);this.Z.R(a,"crn_captions",this.zO,this);this.Z.R(a,"crx_captions",this.AO,this);n5(this,o5(this,"display-settings")||{})},ZBa=function(a){if(1==a.C.Eh||1==a.A.Eh||"alwayson"==g.ZO(a.A,"yt:cc"))return!0;
if(2==a.C.Eh){var b=o5(a,"module-enabled");if(null!=b)return!!b}if(a.A.captionTracks.length)var c=a.player.getAudioTrack().Rs;return"ON"==c||"on"==g.ZO(a.A,"yt:cc")},q5=function(a,b){if(a.o&&(void 0===b||!b)||!a.A.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.lp||"FORCED_ON"==c.Rs},s5=function(a,b){if(a.B){var c=a5(a.B.A,b||a.ma);
if(a.H&&a.H.o)return a.H.o;for(var d=[a.A.Dh,a.C.Dh,g.ZO(a.A,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(t4(c[f])==d[e])return c[f];return a.H&&a.H.wt?a.H.wt:(d=c.find(function(a){return a.isDefault}))?d:c[0]||r5(a)}return null},r5=function(a){return a.H&&a.H.lp},$Ba=function(a,b){for(var c=g.uU(a.T).oa().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},u5=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.K=c,a.K&&t5(a,"module-enabled",!!b));a.o=b;q5(a)&&(a.o=r5(a));a.load(d)},aCa=function(a,b){var c=g.o_(a.ka,!0).height;
if(!c)return null;var d=a.ka.Va();switch(null!=b.params.bv?b.params.bv:b.params.FX?2:1<b.A.length?1:0){case 1:return new j5(b,a.D,a.G,c,d.width,d.height);case 2:return new k5(b,a.D,a.G,c,d.width,d.height);default:return new z4(b,a.D,a.G,c,d.width,d.height)}},n5=function(a,b,c){var d=v5.ob;
a.D={};g.Ea(a.D,v5);a.D.ob={};g.Ea(a.D.ob,d);a.G={ob:{}};var e=b.backgroundOverride?a.G:a.D,f=b.background||d.background;Q4.test(f);e.ob.background=f;e=b.colorOverride?a.G:a.D;f=b.color||d.color;Q4.test(f);e.ob.color=f;e=b.windowColorOverride?a.G:a.D;f=b.windowColor||v5.windowColor;Q4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.G:a.D;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.ob.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.G:a.D;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.ob.fontSizeIncrement=f;f=b.fontStyleOverride?a.G:a.D;e=b.fontStyle;null==e&&(e=d.bold&&d.Ff?3:d.bold?1:d.Ff?2:0);f=f.ob;switch(e){case 1:f.bold=!0;delete f.Ff;break;case 2:delete f.bold;f.Ff=!0;break;case 3:f.bold=!0;f.Ff=!0;break;default:delete f.bold,delete f.Ff}e=b.textOpacityOverride?a.G:a.D;f=b.textOpacity;null==f&&(f=d.textOpacity);e.ob.textOpacity=f;e=b.windowOpacityOverride?a.G:a.D;f=b.windowOpacity;null==f&&(f=v5.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.G:a.D;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.ob.charEdgeStyle=f;e=b.fontFamilyOverride?a.G:a.D;f=b.fontFamily;null==f&&(f=d.fontFamily);e.ob.fontFamily=f;a.loaded&&a.vx();c&&t5(a,"display-settings",b)},cCa=function(a,b){if(b&&!a.J){var c=y4({Bl:0,
lang:"en-GB"});a.J=[c,new v4(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.nU(a.player,a.J)}else!b&&a.J&&(bCa(a,a.J),a.J=null)},bCa=function(a,b){g.qU(a.player,b);
(0,g.D)(b,function(a){g.Ra(this.L,a)},a);
a.ba.wk()},dCa=function(a,b){return a&&g.v(a)&&Q4.test(a)?a:b},eCa=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},fCa=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?g.ld(a,-2,4):b},o5=function(a,b){if(!a.aa)return null;
try{var c=a.aa.get(b)}catch(d){a.aa.remove(b)}return c},t5=function(a,b,c){if(a.aa)try{a.aa.set(b,c)}catch(d){}};
g.DQ.prototype.dk=g.ca(9,function(){for(var a=g.Ad(window.document,"track",void 0,this.o),b=0;b<a.length;b++)g.Td(a[b])});
g.FS.prototype.dk=g.ca(8,function(){this.o.dk()});
g.DQ.prototype.Vn=g.ca(7,function(){return!!this.o.textTracks});
g.FS.prototype.Vn=g.ca(6,function(){return this.o.Vn()});
g.DQ.prototype.Tl=g.ca(5,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.FS.prototype.Tl=g.ca(4,function(a){this.o.Tl(a)});
g.mJ.prototype.yp=g.ca(2,function(a){return(a=this.Jh(a))?a.A:0});
g.vL.prototype.yp=g.ca(1,function(){return 0});
g.QH.prototype.K=g.ca(0,function(a){return a?this.toString()==a.toString():!1});
var RBa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,Q4=/^#(?:[0-9a-f]{3}){1,2}$/i;var rBa=["left","right","center","justify"];var v5={windowColor:"#080808",windowOpacity:0,textAlign:2,Jg:7,Gf:50,sh:100,ob:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(v4,g.vQ);g.r(w4,g.vQ);var x4=0;g.r(z4,g.W);g.h=z4.prototype;g.h.AQ=function(a,b){var c=g.Mh(this.element,this.element.parentElement);this.ia=a-c.x;this.ka=b-c.y;g.T(this.element,"ytp-dragging")};
g.h.zQ=function(a,b){var c=g.Qh(this.element),d=a-this.ia-.02*this.Ca,e=b-this.ka-.02*this.za,f=(d+c.width/2)/this.ca*3;f=Math.floor(g.ld(f,0,2));var k=(e+c.height/2)/this.ma*3;k=Math.floor(g.ld(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.ca;d=100*g.ld(d,0,1);c=(e+k/2*c.height)/this.ma;c=100*g.ld(c,0,1);this.H.params.Jg=l;this.H.params.sh=c;this.H.params.Gf=d;this.B.Jg=l;this.B.sh=c;this.B.Gf=d;this.yF()};
g.h.yQ=function(){g.Bq(this.element,"ytp-dragging")};
g.h.yF=function(){this.Hj(this.D)};
g.h.Yb=function(){return this.type};
g.h.Hj=function(a){var b=Math.min(this.EA(),this.ca),c=this.DA();g.wh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Hs(a);a={transform:"",top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var d=.96*this.B.Gf+2,e=this.B.Jg;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.C.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=
b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-d+"%"}b=.96*this.B.sh+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.wh(this.element,a)};
g.h.Hs=function(a){var b;for(b=0;b<a.length&&a[b]==this.D[b];b++);if(this.N||this.D.length>b)b=0,this.N=!1,this.D=[],this.G=[],this.J=[],this.F=null,g.Rd(this.C);for(;b<a.length;b++)sBa(this,a[b])};
g.h.EA=function(){return 0};
g.h.DA=function(){return 0};tBa.prototype.D=function(){};C4.prototype.clear=function(){this.C=this.A=this.mode=0;this.o=[];this.reset()};
C4.prototype.reset=function(){this.mode=0;this.D.reset(0);this.F.reset(1)};
var uBa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];D4.prototype.set=function(a){this.o=a};
D4.prototype.get=function(){return this.o};
E4.prototype.clear=function(){this.o=0};
E4.prototype.update=function(){this.o=2==this.o?1:0};
E4.prototype.matches=function(a,b){return 0!=this.o&&a==this.B&&b==this.A};
F4.prototype.So=function(a){this.Pe=a.Pe;this.timestamp=a.timestamp};
F4.prototype.reset=function(){this.timestamp=this.Pe=0};
G4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0==d.Pe?a+"_":a+String.fromCharCode(d.Pe)}a+="\n"}return a};
G4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.o=0;this.A=this.row=1};
var zBa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],ABa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],BBa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],CBa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];M4.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.A=this.F;this.B=this.G;this.o=this.A;var c=(a<<2)+(b<<1);this.F.reset(c);this.G.reset(c);this.H.reset((a<<2)+(b<<1)+1)};
B4.prototype.reset=function(a){this.D=a;this.o.clear();this.C=this.B;this.B.reset(a,0);this.F.reset(a,1)};g.r(O4,g.M);O4.prototype.reset=function(){};g.r(P4,O4);P4.prototype.B=function(a){var b=a.firstChild;a=[];this.o||(this.o=y4(this.A),a.push(this.o));b=Array.from(b.childNodes);b=g.q(b);for(var c=b.next();!c.done;c=b.next())IBa(c.value,this.o.id,a);return a};g.r(R4,O4);
R4.prototype.B=function(a){var b=a.firstChild;a=[];this.o||(this.o=y4(),this.A[this.o.id]=this.o,a.push(this.o));for(b=b.firstChild;b;){switch(b.tagName){case "window":var c=b,d=c.getAttribute("id");a:{var e=c,f=this.A[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||
(f=y4());var k={};f&&(g.Ea(k,f.params),f=f.params.ob)&&(k.ob={},g.Ea(k.ob,f));e.getAttribute("rc")&&(k.ar=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.Zs=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.Jg=0>f||8<f?7:f);e.getAttribute("ah")&&(k.Gf=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.sh=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.Bl=1,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.Bl=0));e.getAttribute("bc")&&(k.ob||(k.ob={}),k.ob.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.ob||(k.ob={}),k.ob.backgroundOpacity=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.ob||(k.ob={}),k.ob.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.FX=(0,window.parseInt)(e.getAttribute("sd"),
10));f=(0,window.parseInt)(e.getAttribute("d"),10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"_"+x4++;c=new w4(c,f,0,e,k)}else c=null}this.A[d]=c;a.push(c);break;case "text":for(d=[],IBa(b,this.o.id,d),d=g.q(d),c=d.next();!c.done;c=d.next())c=c.value,this.A[c.windowId]&&a.push(c)}b=b.nextSibling}return a};g.r(S4,O4);S4.prototype.reset=function(){this.H={};this.A=this.o=null;this.G=!0};
S4.prototype.B=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.C,l={},m=c.getAttribute("p");m&&g.Ea(l,this.C[m]);m=U4(c,"b");null!=m&&(l.bold=
m);m=U4(c,"i");null!=m&&(l.Ff=m);m=U4(c,"u");null!=m&&(l.underline=m);m=V4(c,"et");null!=m&&(l.charEdgeStyle=m);m=V4(c,"of");null!=m&&(l.offset=m);m=W4(c,"bc");null!=m&&(l.background=m);m=W4(c,"ec");null!=m&&(l.Fz=m);m=W4(c,"fc");null!=m&&(l.color=m);m=V4(c,"fs");void 0!=m&&0!=m&&(l.fontFamily=m);m=T4(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=T4(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);c=T4(c,"fo");void 0!=c&&(l.textOpacity=c/255);k[d]=l;break;case "ws":d=c.getAttribute("id");this.K[d]=
JBa(this,c);break;case "wp":d=c.getAttribute("id"),this.J[d]=KBa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.o=LBa(this,d,e,!1);g.N(this,this.o);(d=this.H[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.H[this.o.id]=this.o;c.push(this.o);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.D;m=!!U4(d,"a");n=(T4(d,"t")||0)+n;var p=T4(d,"d")||5E3;m||(!this.G&&this.A&&this.A.windowId==
l&&this.A.end>n&&(this.A.end=n),this.A&&"\n"==this.A.text&&(this.A.text=""));var t=m?6:5,w=this.C[d.getAttribute("p")],z=d.childNodes;z.length&&(this.G=null!=d.getAttribute("d"));for(var E=0;E<z.length;E++){var J=z[E];0<E&&(m=!0);var Q=void 0;1==J.nodeType&&(Q=J);if(Q&&"s"==Q.tagName){var da=Q;J=n;Q=p;var Ta=l,vb=m,pc=t,Je=da.textContent?da.textContent:"",ib=this.C[da.getAttribute("p")];da=T4(da,"t")||0;J=new v4(J+da,Q-da,pc,Ta,Je,vb,ib)}else J=new v4(n,p,t,l,J.textContent||"",m,w);k.push(J);this.A=
J}if(0<k.length)for(k[0].windowId==this.D&&(this.o=LBa(this,d,e,!0),g.N(this,this.o),c.push(this.o)),d=g.q(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.o.id,l=this.o,g.N(l,k),l.A.push(k),c.push(k)}e=c}else e=[];return e};g.r(X4,tBa);X4.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+x4++;c=c/1E3-this.G;d=d/1E3-this.G;a=new w4(c,d-c,5,f,{textAlign:0,Jg:0,Gf:2.5*b,sh:5.33*a});e=new v4(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.r($4,O4);$4.prototype.B=function(a){a=new X4(a,a.byteLength,this.A);if(MBa(a)){for(;a.o<a.A.byteLength;)for(0==a.version?a.C=Z4(a)*(1E3/45):1==a.version&&(a.C=4294967296*Z4(a)+Z4(a)),a.F=Y4(a);0<a.F;a.F--){var b=Y4(a),c=Y4(a),d=Y4(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.o,b.o.push({time:a.C,type:this.track,Az:c,Bz:d,order:b.o.length}))}yBa(this.o,a);return a.B}return[]};
$4.prototype.reset=function(){this.o.clear()};g.r(c5,O4);
c5.prototype.B=function(a,b){for(var c=[],d=a.split(gCa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!hCa.test(f)){var l=w5.exec(f);if(l&&4<=l.length){var m=d5(l[1]),n=d5(l[2])-m;m+=k;var p,t=p=void 0,w=void 0,z=void 0,E=l[3];l={textAlign:2};E=g.q(E?E.split(" "):[]);for(var J=E.next();!J.done;J=E.next())if(J=J.value.split(":"),2==J.length){var Q=J[1];switch(J[0]){case "line":J=Q.split(",");J[0].endsWith("%")&&(z=J[0],l.sh=Number.parseInt(z,10),2==J.length&&(w=J[1].trim()));break;case "position":J=Q.split(",");
t=J[0];l.Gf=Number.parseInt(t,10);2==J.length&&(p=J[1].trim());break;case "align":switch(Q){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}z||(l.sh=100,w||(w="end"));if(!t)switch(l.textAlign){case 0:l.Gf=0;break;case 1:l.Gf=100;break;default:l.Gf=50}t=0;switch(w){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(p){case "line-left":t+=0;break;case "center":t+=1;break;case "line-right":t+=2;break;default:switch(l.textAlign){case 0:t+=
0;break;case 2:t+=1;break;case 1:t+=2}}l.Jg=0>t||8<t?7:t;p=l;f=f.substring(w5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=QBa(m,n,5,t),n=new v4(m,n,5,k.id,p,!1,g.Yb(f)?void 0:f),c.push(k),c.push(n),g.N(k,n),k.A.push(n);else for(w=p.split(iCa),1==w.length?(p=5,t=QBa(m,n,p,t)):(z=p=6,t=Object.assign({Zs:32},t),t=new w4(m,n,z,"_"+x4++,t)),c.push(t),z=m,l=0;l<w.length;l++)E=w[l],0==l%2?(J=g.is("<html>"+E+"</html>"),J.getElementsByTagName("parsererror").length?
(Q=J.createElement("span"),Q.appendChild(J.createTextNode(E))):Q=J.firstChild,PBa(this,z,n-(z-m),p,t,0<l,Q,f,c)):z=d5(E)+k}w5.lastIndex=0}}return c};
var hCa=/^NOTE/,gCa=/(?:\r\n|\r|\n){2,}/,w5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),iCa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(e5,g.M);e5.prototype.de=function(){this.o=null};
e5.prototype.X=function(){g.M.prototype.X.call(this);this.de()};
e5.prototype.fF=function(){return!1};g.r(f5,e5);g.h=f5.prototype;g.h.Vu=function(a,b){var c=this.Fm(a),d=(0,g.B)(function(c){this.B=null;b(c.responseText,a)},this);
this.de();this.B=g.rE(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
g.h.Wu=function(a,b,c,d){this.C=c;if(d)for(b=g.q(d.captionTracks),c=b.next();!c.done;c=b.next())b5(this.A,c.value);a()};
g.h.Fm=function(a){var b=a.Xa(),c={};if(this.C||a.B)c.fmt=this.C||"srv"+a.B;a.o&&(c.tlang=a.o.languageCode);return g.jE(b,c)};
g.h.de=function(){e5.prototype.de.call(this);this.B&&this.B.abort()};
g.h.X=function(){this.de();e5.prototype.X.call(this)};g5.prototype.contains=function(a){a=g.bb(this.wb,a);return 0<=a||0>a&&1==(-a-1)%2};
g5.prototype.length=function(){return this.wb.length/2};g.r(h5,g.M);g.h=h5.prototype;g.h.X=function(){g.M.prototype.X.call(this);this.A&&this.A.cancel()};
g.h.dD=function(a){var b=this;if(this.H.Jk())var c=this.D.R(this.B,"progresssync",function(){b.H.index.Pb()&&(b.reset(),b.o=null,UBa(b,b.B.getCurrentTime()),b.D.Ha(c))});
else UBa(this,a)};
g.h.reset=function(){this.F=new g5;this.A&&(this.A.cancel(),this.A=null)};
g.h.WB=function(){var a;if(a=null!==this.o)a=this.o,a=a.o.jh(a);!a||this.A||this.o&&30<this.o.startTime-this.B.getCurrentTime()||(a=this.o,a=a.o.Sk(a),!g.Y(this.B).experiments.o("disable_captions_unknown_requests")&&!a.o[0].duration)||(this.F.contains(a.o[0].Aa)||VBa(this,a),this.o=g.Ga(a.o));this.K.start()};
g.h.kV=function(a){var b=!(this.G?a.response:a.responseText)||400<=a.status;if(!g.Y(this.B).experiments.o("disable_captions_redirects_redux")){var c=g.AL(a);if(c){a=g.dL(this.C,this.L,{});b=this.C;g.ZK(b.A,a,c);b.requestId=a.get("req_id");VBa(this,this.C);return}}b||null===this.J||(this.G?this.J(a.response,1E3*(this.C.o[0].startTime+u4(this.B))):this.J(a.responseText,1E3*(this.C.o[0].startTime+u4(this.B))));this.A=this.C=null};g.r(i5,e5);g.h=i5.prototype;g.h.Vu=function(a,b){this.de();var c=WBa(this,a.A);if(c&&c.index){var d=c.index.yp(c.index.Af());g.Y(this.T).experiments.o("html5_disable_caption_starttime")||(d-=c.index.Zd(c.index.Af()));d*=1E3;this.C=new h5(new g.GK,this.T,c,function(c,f){b(c,a,f,d)},this.G||g.dI(c.info),(0,g.B)(function(){this.C&&this.C.reset();
this.o&&this.o.reset();this.D=!0},this))}};
g.h.fF=function(){var a=this.D;this.D=!1;return a};
g.h.Wu=function(a){if(this.G)b5(this.A,new g.QH({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})),b5(this.A,new g.QH({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}));else for(var b in this.B.o){var c=this.B.o[b];if(g.gI(c.info.mimeType)&&"rawcc"!=b){var d="en",e="English",f=".en",k="";if(c=c.info.captionTrack)d=c.languageCode,e=c.displayName,f=c.vssId,
g.Y(this.T).experiments.o("web_player_populate_live_caption_track_kind_killswitch")||(k=c.kind);b5(this.A,new g.QH({format:1,languageCode:d,languageName:e,name:"",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:f,kind:k}))}}a()};
g.h.de=function(){e5.prototype.de.call(this);this.C&&(this.C.dispose(),this.C=null)};
g.h.Fm=function(){return""};
g.h.X=function(){this.de();e5.prototype.X.call(this)};g.r(j5,z4);j5.prototype.Hs=function(a){var b=this.H.A;z4.prototype.Hs.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.A==e)var d=f;else{d={};g.Ea(d,c.A);g.Ea(d,jCa);var e=c.A;var f=d}sBa(this,c,d)}};
var jCa={gu:!0};g.r(k5,z4);g.h=k5.prototype;g.h.yF=function(){g.nu(this.ga)};
g.h.pV=function(){g.Bq(this.element,"ytp-rollup-mode");this.Hj(this.ua,!0)};
g.h.EA=function(){return this.L};
g.h.DA=function(){return this.H.params.ar*l5(this)};
g.h.Hj=function(a,b){this.ua=a;if(l5(this)){for(var c=0,d=0;d<this.D.length&&c<a.length;d++)this.D[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.D.concat(a.slice(c)));c=this.L;this.L=0;z4.prototype.Hj.call(this,a);d=this.C.offsetWidth+1;this.L=Math.max(YBa(this),c,d);c=this.H.params.ar*l5(this)-this.C.offsetHeight;c!=this.aa&&(b||(0,window.isNaN)(this.aa)||(g.T(this.element,"ytp-rollup-mode"),g.mu(this.ga)),g.wh(this.C,"transform",c?"translateY("+c+"px)":""),this.aa=c);z4.prototype.Hj.call(this,a)}else z4.prototype.Hj.call(this,
a)};g.r(m5,e5);g.h=m5.prototype;g.h.Vu=function(a,b){var c=this.Fm(a),d=(0,g.B)(function(c){this.B=null;b(c.responseText,a)},this);
this.de();this.B=g.rE(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
g.h.Wu=function(a,b,c){var d=this.D;b={type:"list",tlangs:1,v:this.C,fmts:Number(b||!1),vssids:1};this.CB&&(b.asrs=1);d=g.jE(d,b);b=(0,g.B)(function(b){this.B=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.A,e=g.q(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value;l=m.getAttribute("formats");var n=m.getAttribute("lang_code"),p=m.getAttribute("lang_translated"),t=m.getAttribute("name"),w=m.getAttribute("kind"),z=m.getAttribute("id"),E="true"==m.getAttribute("lang_default"),
J="true"==m.getAttribute("cantran");m=m.getAttribute("vss_id");b5(d,new g.QH({formats:l,format:c,languageCode:n,languageName:p,name:t,kind:w,id:z,is_servable:!0,is_translateable:J,vss_id:m,is_default:E}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),p=b[e].getAttribute("lang_original"),t=b[e].getAttribute("id"),w="true"==b[e].getAttribute("lang_default"),l={languageCode:l,languageName:n,languageOriginal:p,id:t,
is_default:w},this.G[l.languageCode]=l.languageName,this.F.push(new g.PH(l))}a()},this);
this.de();this.B=g.rE(d,{format:"RAW",onSuccess:b,withCredentials:!0})};
g.h.Fm=function(a){var b=this.D,c={v:this.C,type:"track",lang:a.A,name:a.F,kind:a.C,fmt:a.B};a.o&&(c.tlang=t4(a));return b=g.jE(b,c)};
g.h.de=function(){e5.prototype.de.call(this);this.B&&this.B.abort()};
g.h.X=function(){this.de();e5.prototype.X.call(this)};g.r(p5,g.DU);g.h=p5.prototype;g.h.X=function(){if(this.F){var a=g.uU(this.T);a&&a.dk()}else cCa(this,!1);g.DU.prototype.X.call(this)};
g.h.xC=function(){return this.F?!this.A.Ka:this.ga||q5(this)?!0:ZBa(this)};
g.h.load=function(a){g.DU.prototype.load.call(this);this.H=this.player.getAudioTrack();if(this.B||a)this.o&&(this.F&&!this.C.experiments.o("disable_native_caption_api")?$Ba(this,!0):a?this.PE(a,this.o):3!=this.player.Ta()&&this.B.Vu(this.o,(0,g.B)(this.PE,this))),this.o&&this.o!=r5(this)?this.player.ya("captionschanged",s4(this.o)):this.player.ya("onCaptionsTrackListChanged");else{var b;XBa(this.A,this.T)?b=new i5(this.A.sa,this.player):this.A.captionTracks.length?b=new f5(this.A):b=new m5(this.A.Jo,
this.A.videoId,this.A.Dh||this.C.Dh||g.ZO(this.A,"yt:cc_default_lang")||this.C.ia,this.A.Io);this.B=b;g.N(this,this.B);b.Wu((0,g.B)(this.TV,this),!0,this.F?"vtt":void 0,this.player.getAudioTrack())}};
g.h.unload=function(){this.F?this.C.experiments.o("disable_native_caption_api")?g.uU(this.T).dk():this.o&&$Ba(this,!1):(this.ca&&g.ou(this.ca),g.rU(this.player,"captions"),this.L=[],this.B&&this.B.de(),this.J&&g.nU(this.player,this.J),this.vx());g.DU.prototype.unload.call(this);var a=g.cU(this.player.app);a&&a.C&&g.qP(a.C.B);this.player.ya("captionschanged",{})};
g.h.TV=function(){var a;this.K||ZBa(this)?a=s5(this,this.K):q5(this)&&(a=r5(this));if(this.F||this.ga){for(var b=a5(this.B.A,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.RH(e),srclang:t4(e),id:e.toString()};this.ga||(f.src=this.B.Fm(e));e==a&&(f["default"]=1);c.push(g.L("TRACK",f))}g.uU(this.T).Tl(c);(a=g.uU(this.T).oa())&&a.textTracks&&a.textTracks.addEventListener&&!this.C.experiments.o("disable_native_caption_api")&&this.Z.R(a.textTracks,"change",this.UV)}else!this.o&&a&&
u5(this,a),this.player.ya("onCaptionsTrackListChanged"),this.player.ya("onApiChange")};
g.h.UV=function(){for(var a=g.uU(this.T).oa().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=a5(this.B.A,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.o:null)!=b&&u5(this,b,!0)};
g.h.SX=function(){this.C.experiments.o("disable_native_caption_api")?this.loaded&&!this.F&&this.unload():!this.o&&this.F||this.unload()};
g.h.PE=function(a,b,c,d){if(a){this.B.fF()&&(this.L=[],g.rU(this.T,"captions"),this.ba.wk());a=TBa(this.B,a,b,c,d);g.nU(this.player,a);if(this.K&&!this.ga&&this.o!=r5(this)){!this.K||g.GM(this.C)||g.OM(this.C)||(g.ou(this.ca),a=y4({Jg:0,Gf:5,sh:5,ar:2,textAlign:0,Bl:0,lang:"en-GB"}),this.P=[a],b=["Click "," for settings"],this.ia||(c=new g.tH(g.Mqa()),g.N(this,c),this.ia=c.element),c=a.end-a.start,(d=g.RH(this.o))&&this.P.push(new v4(a.start,c,0,a.id,d)),this.P.push(new v4(a.start,c,0,a.id,b[0]),
new v4(a.start,c,0,a.id,this.ia,!0),new v4(a.start,c,0,a.id,b[1],!0)),g.nU(this.player,this.P),g.mu(this.ca));if(this.K||g.GM(this.C))t5(this,"module-enabled",!0),this.H&&(this.H.o=this.o);(a=g.cU(this.player.app))&&a.C&&g.qP(a.C.B)}this.K=!1}};
g.h.zO=function(a){this.L.push(a);this.ba.wk()};
g.h.AO=function(a){g.Ra(this.L,a);var b=this.B instanceof i5&&this.B.G;!this.C.experiments.o("disable_remove_displayed_close_caption_cue")&&b&&g.qU(this.player,[a]);this.ba.wk()};
g.h.OW=function(a){if(a instanceof w4){var b=this.N[a.id];b&&b.H!=a&&(b.dispose(),delete this.N[a.id],b=null);b||(b=aCa(this,a))&&(this.N[a.id]=b)}else b=a.windowId,this.Y[b]||(this.Y[b]=[]),this.Y[b].push(a)};
g.h.VW=function(){bCa(this,this.P);this.P=null};
g.h.HG=function(){this.ba.stop();g.Zb(this.Y);this.L.sort(g.wQ);var a=this.L;if(this.J){var b=(0,g.Ud)(a,function(a){return-1==this.J.indexOf(a)},this);
b.length&&(a=b)}(0,g.D)(a,this.OW,this);g.Hb(this.N,function(a,b){this.Y[b]?(a.element.parentNode||g.tU(this.player,a.element,4),a.Hj(this.Y[b])):(a.dispose(),delete this.N[b])},this)};
g.h.xF=function(){n5(this,{},!0)};
g.h.Qt=function(){var a=v5.ob;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Ff?3:a.bold?1:a.Ff?2:0,textOpacity:a.textOpacity,windowColor:v5.windowColor,windowOpacity:v5.windowOpacity};var b=o5(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.yx=function(a,b){var c={};g.Ea(c,o5(this,"display-settings"));g.Ea(c,a);n5(this,c,b);this.player.V("captionssettingschanged")};
g.h.vx=function(){!this.F&&this.loaded&&(g.Hb(this.N,function(a,b){a.dispose();delete this.N[b]},this),this.HG())};
g.h.kv=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.ld(b,-2,4);this.yx({fontSizeIncrement:c});return c;case "reload":b&&!this.F&&u5(this,this.o,!0);break;case "stickyLoading":void 0!=b&&this.C.Lb&&t5(this,"module-enabled",!!b);break;case "track":if(!this.B)return{};if(b){if(this.F)break;if(!g.Aa(b))break;if(g.Yb(b)){u5(this,null,!0);break}var d;c=a5(this.B.A,!0);for(var e=0;e<c.length;e++){var f=c[e];f.A!=b.languageCode||d&&f.D!=b.languageName||(d=b.translationLanguage?
pBa(f,b.translationLanguage):f)}!d||d==this.o&&this.loaded||u5(this,d,!0)}else return this.loaded&&this.o&&this.o!=r5(this)?s4(this.o):{};return"";case "tracklist":return this.B?(0,g.I)(a5(this.B.A,!(!b||!b.includeAsr)),function(a){return s4(a)}):[];
case "translationLanguages":return this.B?this.B.F:[];case "displaySettings":d=this.Qt();if(g.GM(this.C)&&b&&g.Aa(b))if(b.reset)this.xF();else{f={};for(c in b)switch(c){case "color":case "background":case "windowColor":f[c]=dCa(b[c],d[c]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[c]=eCa(b[c],d[c]);break;case "charEdgeStyle":var k=g.k1[b[c]];f[c]=g.ta(k)?k:d[c];break;case "fontSizeIncrement":f[c]=fCa(b[c],d[c]);break;case "fontFamilyOption":k=g.j1[b[c]];f.fontFamily=
g.ta(k)?k:d[c];break;case "fontStyle":k=g.l1[b[c]],f[c]=g.ta(k)?k:d[c]}for(e in f)f[e+"Override"]=!0;this.yx(f,!0);d=this.Qt()}d.fontFamilyOption=g.Xwa[d.fontFamily];d.charEdgeStyle=g.Ywa[d.charEdgeStyle];d.fontStyle=g.Zwa[d.fontStyle];return d;case "sampleSubtitles":this.F||void 0==b||cCa(this,!!b);break;case "xmlTrack":b&&this.C.Lb&&(this.F||u5(this,new g.QH({languageName:b.name}),!1,b.xml))}};
g.h.yO=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.C.Lb&&a.push("stickyLoading","xmlTrack");return a};
g.h.Wg=function(){var a=this.o;return a?{cc:a.G}:{}};
g.h.xG=function(){this.loaded&&this.o&&this.o!=r5(this)?(t5(this,"module-enabled",!1),this.unload(),q5(this,!0)&&u5(this,r5(this),!1)):u5(this,this.o==r5(this)?s5(this,!0):this.o,!0)};
g.h.iS=function(){var a=this.o==r5(this);q5(this,a)?u5(this,this.player.getAudioTrack().lp,!1):this.A.captionTracks.length&&(this.loaded&&this.unload(),this.xC()&&(a?u5(this,s5(this),!1):this.load()))};g.AX.captions=p5;})(_yt_player);
