(function(g){var window=this;var PCa=function(a,b){return g.Tb(a,b)},i6=function(a){g.Rm(a,"zx",g.ub());
return a},j6=function(a,b,c){g.xa(c)||(c=[String(c)]);
g.Um(a.o,b,c)},QCa=function(a,b){var c=[];
g.Hk(b,function(a){try{var b=g.oD.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.u(b)?g.nD(b)&&c.push(a):c.push(a)},a);
return c},RCa=function(a,b){var c=QCa(a,b);
(0,g.D)(c,function(a){g.oD.prototype.remove.call(this,a)},a)},SCa=function(a){if(a.Kd){if(a.Kd.locationOverrideToken)return{locationOverrideToken:a.Kd.locationOverrideToken};
if(null!=a.Kd.latitudeE7&&null!=a.Kd.longitudeE7)return{latitudeE7:a.Kd.latitudeE7,longitudeE7:a.Kd.longitudeE7}}return null},TCa=function(a,b,c,d){var e=new g.Im(null,void 0);
a&&g.Jm(e,a);b&&g.Km(e,b);c&&g.Lm(e,c);d&&g.Mm(e,d);return e},UCa=function(a){g.UF[a]&&(a=g.UF[a],(0,g.D)(a,function(a){g.SF[a]&&delete g.SF[a]}),a.length=0)},VCa=function(a){var b=g.RF();
if(b)if(b.clear(a),a)UCa(a);else for(var c in g.UF)UCa(c)},k6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.Cm;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",WCa(this,a.capabilities||""),XCa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",
this.o=a.localChannelEncryptionKey||"")},WCa=function(a,b){a.capabilities.clear();
(0,g.Ud)(b.split(","),g.Da(PCa,YCa)).forEach(function(b){a.capabilities.add(b)})},XCa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},l6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},m6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},ZCa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},$Ca=function(a){return new l6(a)},aDa=function(a){return g.xa(a)?(0,g.I)(a,$Ca):[]},n6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},o6=function(a){return g.xa(a)?"["+(0,g.I)(a,n6).join(",")+"]":"null"},p6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},bDa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},q6=function(a,b){return g.Ia(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},r6=function(a,b){return g.Ia(a,function(a){return m6(a,b)})},cDa=function(){var a=(0,g.SG)();
a&&RCa(a,a.o.ie(!0))},s6=function(){var a=g.VG("yt-remote-connected-devices")||[];
g.db(a);return a},dDa=function(a){if(g.Na(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},eDa=function(a){g.UG("yt-remote-connected-devices",a,86400)},u6=function(){if(t6)return t6;
var a=g.VG("yt-remote-device-id");a||(a=p6(),g.UG("yt-remote-device-id",a,31536E3));for(var b=s6(),c=1,d=a;g.Ma(b,d);)c++,d=a+"#"+c;return t6=d},v6=function(){var a=s6(),b=u6();
g.Ma(a,b);g.XG()&&g.fb(a,b);a=dDa(a);if(g.Na(a))try{g.CG("remote_sid")}catch(c){}else try{g.BG("remote_sid",a.join(","),-1)}catch(c){}},fDa=function(){return g.VG("yt-remote-session-browser-channel")},gDa=function(){return g.VG("yt-remote-local-screens")||[]},hDa=function(){g.UG("yt-remote-lounge-token-expiration",!0,86400)},iDa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(gDa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.qm)(c,function(a){return!g.Ma(b,a)})&&hDa();
g.UG("yt-remote-local-screens",a,31536E3)},jDa=function(a,b){g.UG("yt-remote-session-browser-channel",a);
g.UG("yt-remote-session-screen-id",b);var c=s6(),d=u6();g.Ma(c,d)||c.push(d);eDa(c);v6()},w6=function(a){a||(g.WG("yt-remote-session-screen-id"),g.WG("yt-remote-session-video-id"));
v6();a=s6();g.Ra(a,u6());eDa(a)},kDa=function(){if(!x6){var a=g.zD();
a&&(x6=new g.iD(a))}return x6?!!x6.get("yt-remote-use-staging-server"):!1},lDa=function(){var a=window.document.createElement("a");
g.hd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.zb(a)},mDa=function(a,b,c){c=void 0===c?null:c;
var d=g.Nd("SCRIPT");d.id=a;d.onload=function(){b&&(0,window.setTimeout)(b,0)};
d.onreadystatechange=function(){switch(d.readyState){case "loaded":case "complete":d.onload()}};
c&&d.setAttribute("nonce",c);g.jd(d,g.le("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));a=window.document.getElementsByTagName("head")[0]||window.document.body;a.insertBefore(d,a.firstChild);return d},nDa=function(a){a=void 0===a?null:a;
var b=lDa(),c=window.document.getElementById(b),d=c&&g.cF(c,"loaded");d||c&&!d||(c=mDa(b,function(){g.cF(c,"loaded")||(g.bF(c,"loaded","true"),g.YF(b),g.aE(g.Da(VCa,b),0))},a))},oDa=function(){var a=void 0===a?null:a;
window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):nDa(a)},y6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},pDa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},z6=function(a){a.length?qDa(a.shift(),function(){z6(a)}):A6()},rDa=function(a){return"chrome-extension://"+a+B6},qDa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},C6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},A6=function(){var a=pDa();
a&&a(!1,"No cast extension found")},D6=function(){if(sDa){var a=2,b=pDa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;qDa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",A6,c)}},tDa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(D6(),a({command:"cast.sender.init"}))},uDa=function(){D6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);z6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+B6,"//www.gstatic.com/eureka/clank"+B6])},E6=function(a,b,c){g.M.call(this);
this.F=null!=c?(0,g.B)(a,c):a;this.Cd=b;this.D=(0,g.B)(this.xL,this);this.o=!1;this.A=0;this.B=this.Ea=null;this.C=[]},F6=function(){},G6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Z=new g.Ym(this);this.A=new g.Ag;this.A.setInterval(250)},wDa=function(a,b,c){a.yk=1;
a.Sh=i6(b.clone());a.Dj=c;a.D=!0;vDa(a,null)},H6=function(a,b,c,d,e){a.yk=1;
a.Sh=i6(b.clone());a.Dj=null;a.D=c;e&&(a.HF=!1);vDa(a,d)},vDa=function(a,b){a.vl=(0,g.H)();
I6(a);a.zi=a.Sh.clone();j6(a.zi,"t",a.F);a.Zn=0;a.Xc=a.o.tt(a.o.Sn()?b:null);0<a.Zt&&(a.Sq=new g.ml((0,g.B)(a.XG,a,a.Xc),a.Zt));a.Z.W(a.Xc,"readystatechange",a.QW);var c=a.ej?g.cc(a.ej):{};a.Dj?(a.Mr="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Xc.send(a.zi,a.Mr,a.Dj,c)):(a.Mr="GET",a.HF&&!g.Jd&&(c.Connection="close"),a.Xc.send(a.zi,a.Mr,null,c));a.o.Lf(1)},zDa=function(a,b,c){for(var d=!0;!a.Ri&&a.Zn<c.length;){var e=xDa(a,c);
if(e==J6){4==b&&(a.Th=4,K6(15),d=!1);break}else if(e==yDa){a.Th=4;K6(16);d=!1;break}else L6(a,e)}4==b&&0==c.length&&(a.Th=1,K6(17),d=!1);a.Sf=a.Sf&&d;d||(M6(a),N6(a))},xDa=function(a,b){var c=a.Zn,d=b.indexOf("\n",c);
if(-1==d)return J6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return yDa;d+=1;if(d+c>b.length)return J6;var e=b.substr(d,c);a.Zn=d+c;return e},BDa=function(a,b){a.vl=(0,g.H)();
I6(a);var c=b?window.location.hostname:"";a.zi=a.Sh.clone();g.Rm(a.zi,"DOMAIN",c);g.Rm(a.zi,"t",a.F);try{a.Tf=new window.ActiveXObject("htmlfile")}catch(n){M6(a);a.Th=7;K6(22);N6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in O6)k=O6[l];else if(l in ADa)k=O6[l]=ADa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=O6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.kd(g.Ac("b/12014412"),d+"</body></html>");a.Tf.open();a.Tf.write(g.ad(c));a.Tf.close();a.Tf.parentWindow.m=(0,g.B)(a.YV,a);a.Tf.parentWindow.d=(0,g.B)(a.QE,a,!0);a.Tf.parentWindow.rpcClose=(0,g.B)(a.QE,a,!1);c=a.Tf.createElement("DIV");a.Tf.parentWindow.document.body.appendChild(c);d=g.Oc(a.zi.toString());d=g.ob(g.Lc(d));d=g.kd(g.Ac("b/12014412"),'<iframe src="'+d+'"></iframe>');g.gd(c,g.ad(d));a.o.Lf(1)},
I6=function(a){a.Lx=(0,g.H)()+a.C;
CDa(a,a.C)},CDa=function(a,b){if(null!=a.Ml)throw Error("WatchDog timer not null");
a.Ml=P6((0,g.B)(a.oW,a),b)},Q6=function(a){a.Ml&&(g.x.clearTimeout(a.Ml),a.Ml=null)},N6=function(a){a.o.TA()||a.Ri||a.o.Cq(a)},M6=function(a){Q6(a);
g.kf(a.Sq);a.Sq=null;a.A.stop();g.dn(a.Z);if(a.Xc){var b=a.Xc;a.Xc=null;b.abort();b.dispose()}a.Tf&&(a.Tf=null)},L6=function(a,b){try{a.o.IE(a,b),a.o.Lf(4)}catch(c){}},EDa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;DDa(a,b,function(e){e?c(!0):g.x.setTimeout(function(){EDa(a,b,c,d,f)},f)})}},DDa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{R6(d),c(!0)}catch(e){}};
d.onerror=function(){try{R6(d),c(!1)}catch(e){}};
d.onabort=function(){try{R6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{R6(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},R6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},FDa=function(a){this.o=a;
this.A=new F6},GDa=function(a){var b=S6(a.o,a.Wl,"/mail/images/cleardot.gif");
i6(b);EDa(b.toString(),5E3,(0,g.B)(a.BK,a),3,2E3);a.Lf(1)},U6=function(a){var b=a.o.J;
if(null!=b)K6(5),b?(K6(11),T6(a.o,a,!1)):(K6(12),T6(a.o,a,!0));else if(a.Me=new G6(a,void 0,void 0,void 0),a.Me.ej=a.Xt,b=a.o,b=S6(b,b.Sn()?a.Lm:null,a.Yt),K6(5),!g.Hd||g.sc(10))j6(b,"TYPE","xmlhttp"),H6(a.Me,b,!1,a.Lm,!1);else{j6(b,"TYPE","html");var c=a.Me;a=!!a.Lm;c.yk=3;c.Sh=i6(b.clone());BDa(c,a)}},V6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new F6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},HDa=function(a,b){this.o=a;
this.map=b;this.context=null},IDa=function(a){g.nf.call(this,"statevent",a)},JDa=function(a,b){g.nf.call(this,"timingevent",a);
this.size=b},KDa=function(a){g.nf.call(this,"serverreachability",a)},NDa=function(a){LDa(a);
if(3==a.o){var b=a.En++,c=a.mp.clone();g.Rm(c,"SID",a.B);g.Rm(c,"RID",b);g.Rm(c,"TYPE","terminate");W6(a,c);b=new G6(a,a.B,b,void 0);b.yk=2;b.Sh=i6(c.clone());(new window.Image).src=b.Sh;b.vl=(0,g.H)();I6(b)}MDa(a)},ODa=function(a){a.YK(1,0);
a.mp=S6(a,null,a.Wt);X6(a)},LDa=function(a){a.Fh&&(a.Fh.abort(),a.Fh=null);
a.Bc&&(a.Bc.cancel(),a.Bc=null);a.Kg&&(g.x.clearTimeout(a.Kg),a.Kg=null);Y6(a);a.pe&&(a.pe.cancel(),a.pe=null);a.Kh&&(g.x.clearTimeout(a.Kh),a.Kh=null)},PDa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new HDa(a.KR++,b));2!=a.o&&3!=a.o||X6(a)},X6=function(a){a.pe||a.Kh||(a.Kh=P6((0,g.B)(a.OE,a),0),a.mk=0)},RDa=function(a,b){if(1==a.o){if(!b){a.En=Math.floor(1E5*Math.random());
var c=a.En++,d=new G6(a,"",c,void 0);d.ej=null;var e=Z6(a),f=a.mp.clone();g.Rm(f,"RID",c);g.Rm(f,"CVER","1");W6(a,f);wDa(d,f,e);a.pe=d;a.o=2}}else 3==a.o&&(b?QDa(a,b):0==a.A.length||a.pe||QDa(a))},QDa=function(a,b){if(b)if(6<a.Ti){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.En-1;var d=Z6(a)}else c=b.G,d=b.Dj;else c=a.En++,d=Z6(a);var e=a.mp.clone();g.Rm(e,"SID",a.B);g.Rm(e,"RID",c);g.Rm(e,"AID",a.Ok);W6(a,e);c=new G6(a,a.B,c,a.mk+1);c.ej=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.pe=c;wDa(c,e,d)},W6=function(a,b){if(a.Bd){var c=a.Bd.AA();
c&&g.Hb(c,function(a,c){g.Rm(b,c,a)})}},Z6=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.Ti&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.Ti?e:f-d;try{g.Hb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},SDa=function(a){a.Bc||a.Kg||(a.G=1,a.Kg=P6((0,g.B)(a.NE,a),0),a.Zj=0)},$6=function(a){if(a.Bc||a.Kg||3<=a.Zj)return!1;
a.G++;a.Kg=P6((0,g.B)(a.NE,a),TDa(a,a.Zj));a.Zj++;return!0},T6=function(a,b,c){a.Kr=c;
a.kg=b.Yg;a.F||ODa(a)},Y6=function(a){null!=a.Ui&&(g.x.clearTimeout(a.Ui),a.Ui=null)},TDa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},a7=function(a,b){if(2==b||9==b){var c=null;
a.Bd&&(c=null);var d=(0,g.B)(a.EX,a);c||(c=new g.Im("//www.google.com/images/cleardot.gif"),i6(c));DDa(c.toString(),1E4,d)}else K6(2);UDa(a,b)},UDa=function(a,b){a.o=0;
a.Bd&&a.Bd.Cz(b);MDa(a);LDa(a)},MDa=function(a){a.o=0;
a.kg=-1;if(a.Bd)if(0==a.C.length&&0==a.A.length)a.Bd.Us();else{g.Va(a.C);var b=g.Va(a.A);a.C.length=0;a.A.length=0;a.Bd.Us(b)}},S6=function(a,b,c){var d=g.Sm(c);
if(""!=d.A)b&&g.Km(d,b+"."+d.A),g.Lm(d,d.D);else{var e=window.location;d=TCa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.tm&&g.Hb(a.tm,function(a,b){g.Rm(d,b,a)});
g.Rm(d,"VER",a.Ti);W6(a,d);return d},P6=function(a,b){if(!g.za(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},K6=function(a){b7.dispatchEvent(new IDa(b7,a))},VDa=function(){},WDa=function(a,b){this.action=a;
this.params=b||{}},c7=function(a,b){g.M.call(this);
this.o=new g.V(this.PV,0,this);g.N(this,this.o);this.Cd=5E3;this.A=0;if(g.za(a))b&&(a=(0,g.B)(a,b));else if(a&&g.za(a.handleEvent))a=(0,g.B)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},d7=function(a,b,c){this.L=a;
this.F=b;this.B=new g.hD;this.A=new c7(this.oY,this);this.o=this.gb=null;this.K=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.N=c||!1},XDa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Kr,sessionId:a.o.B,arrayId:a.o.Ok}},YDa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&RDa(a.o),NDa(a.o));a.H=0},e7=function(a){return!!a.o&&3==a.o.o},ZDa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},f7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||window.document.location.href;var b=g.Pg(a)||"";b&&(this.port=":"+b);this.domain=g.Og(a)||"";a=g.Fb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.yb(a,"10.0")&&(this.A=!1))},g7=function(a,b){var c=a.o;
if(g.u(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.Yg(c+b,{})},h7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Da(a.C,d,!0),onError:g.Da(a.B,e),Gd:g.Da(a.D,e)};c&&(a.Sb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.rE(b,a)},cEa=function(){var a=$Da;
aEa();i7.push(a);bEa(i7)},j7=function(a,b){aEa();
var c=i7,d=dEa(a,String(b));g.Na(c)?eEa(d):(bEa(c),(0,g.D)(c,function(a){a(d)}))},aEa=function(){i7||(i7=g.y("yt.mdx.remote.debug.handlers_")||[],g.ua("yt.mdx.remote.debug.handlers_",i7,void 0))},eEa=function(a){var b=(k7+1)%50;
k7=b;l7[b]=a;m7||(m7=49==b)},bEa=function(a){var b=l7;
if(b[0]){var c=k7,d=m7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.D)(a,function(a){a(e)})}while(d!=c);
l7=Array(50);k7=-1;m7=!1}},dEa=function(a,b){var c=((0,g.H)()-fEa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},n7=function(a){g.KF.call(this);
this.G=a;this.o=[]},gEa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},hEa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Ud)(a.o,function(a){return!!q6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=gEa(a,b[d])||c;return c},iEa=function(a,b){var c=a.o.length;
a.o=(0,g.Ud)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},o7=function(a,b,c,d){g.KF.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Ea=window.NaN},q7=function(a){n7.call(this,"LocalScreenService");
this.B=a;this.A=window.NaN;p7(this);this.info("Initializing with "+o6(this.o))},jEa=function(a){if(a.o.length){var b=(0,g.I)(a.o,function(a){return a.id}),c=g7(a.B,"/pairing/get_lounge_token_batch");
h7(a.B,c,{screen_ids:b.join(",")},(0,g.B)(a.LL,a),(0,g.B)(a.KL,a))}},p7=function(a){var b=aDa(gDa());
b=(0,g.Ud)(b,function(a){return!a.uuid});
return hEa(a,b)},r7=function(a,b){iDa((0,g.I)(a.o,ZCa));
b&&hDa()},t7=function(a,b){g.KF.call(this);
this.F=b;var c=g.VG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Ma(c,l)}this.o=d;this.D=a;this.B=this.C=window.NaN;this.A=null;s7("Initialized with "+g.Gg(this.o))},kEa=function(a,b,c){var d=g7(a.D,"/pairing/get_screen_availability");
h7(a.D,d,{lounge_token:b.token},(0,g.B)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.B)(function(){c(!1)},a))},u7=function(a,b){a:if(g.Nb(b)!=g.Nb(a.o))var c=!1;
else{c=g.Qb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(s7("Updated online screens: "+g.Gg(a.o)),a.o=b,a.V("screenChange"));lEa(a)},v7=function(a){(0,window.isNaN)(a.B)||g.cE(a.B);
a.B=g.aE((0,g.B)(a.Pw,a),0<a.C&&a.C<(0,g.H)()?2E4:1E4)},s7=function(a){j7("OnlineScreenService",a)},mEa=function(a){var b={};
(0,g.D)(a.F(),function(a){a.token?b[a.token]=a.id:this.tc("Requesting availability of screen w/o lounge token.")});
return b},lEa=function(a){a=g.Qb(g.Ib(a.o,function(a){return a}));
g.db(a);a.length?g.UG("yt-remote-online-screen-ids",a.join(","),60):g.WG("yt-remote-online-screen-ids")},w7=function(a){n7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};nEa(this)},pEa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.Ge();if(k=(c?r6(k,c):null)||r6(k,b)){k.uuid=b;var l=x7(a,k);kEa(a.A,l,function(a){e(a?l:null)})}else c?oEa(a,c,(0,g.B)(function(a){var f=x7(this,new l6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));kEa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},qEa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},oEa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Sb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.rE(g7(a.F,"/pairing/get_lounge_token_batch"),e)},rEa=function(a){a.o=a.B.Ge();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+o6(a.o))},nEa=function(a){y7(a);
a.B=new q7(a.F);a.B.subscribe("screenChange",(0,g.B)(a.ZL,a));rEa(a);a.C=aDa(g.VG("yt-remote-automatic-screen-cache")||[]);y7(a);a.info("Initializing automatic screens: "+o6(a.C));a.A=new t7(a.F,(0,g.B)(a.Ge,a,!0));a.A.subscribe("screenChange",(0,g.B)(function(){this.V("onlineScreenChange")},a))},x7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=r6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.UG("yt-remote-automatic-screen-cache",(0,g.I)(a.C,ZCa)));y7(a);a.D[b.uuid]=b.id;g.UG("yt-remote-device-id-map",a.D,31536E3);return b},y7=function(a){a.D=g.VG("yt-remote-device-id-map")||{}},z7=function(a,b,c){g.KF.call(this);
this.N=c;this.J=a;this.A=b;this.B=null},A7=function(a,b){j7(a.N,b)},B7=function(a,b){z7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.B)(this.uY,this);this.D=(0,g.B)(this.AW,this);this.C=g.aE((0,g.B)(function(){sEa(this,null)},this),12E4)},tEa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Gg(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.A,(0,g.B)(function(){A7(this,"Failed to send message: getMdxSessionStatus.")},a)):A7(a,"Sending yt message without session: "+g.Gg(b))},sEa=function(a,b){g.cE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.B)(a.Dq,a),d=(0,g.B)(a.Le,a);a.JA(b,c,d,5)}}else a.Le(Error("Waiting for session status timed out."))},C7=function(a,b,c){z7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.P=c;this.D=null;this.G=g.A;this.F=window.NaN;this.L=(0,g.B)(this.xY,this);this.o=g.A},uEa=function(a){a.o=a.J.eH(a.K,a.A.label,a.A.friendlyName,(0,g.B)(function(a){this.o=g.A;
this.Dq(a)},a),(0,g.B)(function(a){this.o=g.A;
this.Le(a)},a))},vEa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.P;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}kDa()&&(b.env_useStageMdx=1);return g.Wg(b)},D7=function(a,b){z7.call(this,a,b,"ManualSession");
this.o=g.aE((0,g.B)(this.Qk,this,null),150)},E7=function(a,b,c,d){g.KF.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.B)(this.bV,this)},wEa=function(a,b){return b?g.Ia(a.B,function(a){return m6(b,a.label)},a):null},F7=function(a){j7("Controller",a)},$Da=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},G7=function(a){return a.D||!!a.B.length||!!a.o},H7=function(a,b,c){b!=a.o&&(g.kf(a.o),(a.o=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.A):a.V("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.B)(a.LE,a,b)),b.B?a.V("yt-remote-cast2-session-change",b.B):c&&a.o.Qk(null)):a.V("yt-remote-cast2-session-change",null))},xEa=function(a){var b=a.A.dH(),c=a.o&&a.o.A;
a=(0,g.I)(b,function(a){c&&m6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=wEa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},DEa=function(a,b,c,d,e,f,k){yEa()?zEa(b,e,f,k)&&(J7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?AEa(a,c):(window.__onGCastApiAvailable=function(b,d){b?AEa(a,c):(K7("Failed to load cast API: "+d),L7(!1),J7(!1),g.WG("yt-remote-cast-available"),g.WG("yt-remote-cast-receiver"),BEa(),
c(!1))},d?oDa():C6("CriOS")?tDa():C6("Android")&&C6("Chrome/")&&window.navigator.presentation?uDa():window.chrome&&window.navigator.presentation&&!C6("Edge")?(D6(),z6(CEa.map(rDa))):A6())):I7("Cannot initialize because not running Chrome")},BEa=function(){I7("dispose");
var a=M7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);EEa(!1);g.WF(N7);N7.length=0},O7=function(){return!!g.VG("yt-remote-cast-installed")},FEa=function(){var a=g.VG("yt-remote-cast-receiver");
return a?a.friendlyName:null},GEa=function(){I7("clearCurrentReceiver");
g.WG("yt-remote-cast-receiver")},HEa=function(){return O7()?M7()?M7().getCastSession():(K7("getCastSelector: Cast is not initialized."),null):(K7("getCastSelector: Cast API is not installed!"),null)},Q7=function(){O7()?M7()?P7()?(I7("Requesting cast selector."),M7().requestSession()):(I7("Wait for cast API to be ready to request the session."),N7.push(g.VF("yt-remote-cast2-api-ready",Q7))):K7("requestCastSelector: Cast is not initialized."):K7("requestCastSelector: Cast API is not installed!")},R7=
function(a,b){P7()?M7().setConnectedScreenStatus(a,b):K7("setConnectedScreenStatus called before ready.")},yEa=function(){var a=0<=g.Fb.search(/ (CrMo|Chrome|CriOS)\//);
return g.lI||a},IEa=function(a,b){M7().init(a,b)},zEa=function(a,b,c,d){var e=!1;
M7()||(a=new E7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.UG("yt-remote-cast-available",a);g.ZF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){I7("onReceiverSelected: "+a.friendlyName);
g.UG("yt-remote-cast-receiver",a);g.ZF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){I7("onReceiverResumed: "+a.friendlyName);
g.UG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){I7("onSessionChange: "+n6(a));
a||g.WG("yt-remote-cast-receiver");g.ZF("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
I7("cloudview.createSingleton_: "+e);return e},M7=function(){return g.y("yt.mdx.remote.cloudview.instance_")},AEa=function(a,b){L7(!0);
J7(!1);IEa(a,function(a){a?(EEa(!0),g.YF("yt-remote-cast2-api-ready")):(K7("Failed to initialize cast API."),L7(!1),g.WG("yt-remote-cast-available"),g.WG("yt-remote-cast-receiver"),BEa());b(a)})},I7=function(a){j7("cloudview",a)},K7=function(a){j7("cloudview",a)},L7=function(a){I7("setCastInstalled_ "+a);
g.UG("yt-remote-cast-installed",a)},P7=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},EEa=function(a){I7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},J7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},S7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.o=-1;this.muted=!1;this.audioTrackId=null;this.G=this.H=0;this.A=null;this.hasNext=this.og=!1;this.K=this.J=this.B=this.D=0;this.C=window.NaN;this.F=!1;this.reset(a)},T7=function(a){a.audioTrackId=null;
a.A=null;a.o=-1;a.og=!1;a.hasNext=!1;a.H=0;a.G=(0,g.H)();a.D=0;a.B=0;a.J=0;a.K=0;a.C=window.NaN;a.F=!1},U7=function(a){return a.qb()?((0,g.H)()-a.G)/1E3:0},V7=function(a,b){a.H=b;
a.G=(0,g.H)()},W7=function(a){switch(a.o){case 1:case 1081:return((0,g.H)()-a.G)/1E3+a.H;
case -1E3:return 0}return a.H},X7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&T7(a)},Y7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.o;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.dc(a.A);b.hasPrevious=a.og;b.hasNext=a.hasNext;b.playerTime=a.H;b.playerTimeAt=a.G;b.seekableStart=a.D;b.seekableEnd=a.B;b.duration=a.J;b.loadedTime=a.K;b.liveIngestionTime=a.C;return b},$7=function(a,b){g.KF.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.yC;this.B=this.A=null;this.J=(0,g.B)(this.tS,this);this.G=(0,g.B)(this.Hn,this);this.H=(0,g.B)(this.sS,this);this.K=(0,g.B)(this.FS,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Sx,this),JEa(this))):c=3;0!=c&&(b?this.Sx(c):g.aE((0,g.B)(function(){this.Sx(c)},this),0));
var d=HEa();d&&Z7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},a8=function(a){return new S7(a.C.getPlayerContextData())},JEa=function(a){(0,g.D)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.Da(this.WU,a),this))},a)},KEa=function(a){(0,g.D)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},b8=function(a,b){50>a.D.Cc()&&g.AC(a.D,b)},d8=function(a,b,c){var d=a8(a);
V7(d,c);-1E3!=d.o&&(d.o=b);c8(a,d)},e8=function(a,b,c){a.C.sendMessage(b,c)},c8=function(a,b){KEa(a);
a.C.setPlayerContextData(Y7(b));JEa(a)},Z7=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.Hn(null));
a.B=b;a.B&&(j7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.Hn(a.B.media[0]))},LEa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=a8(a);b.contentId!=d.videoId&&j7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.o=c.playerState;V7(d,a.A.getEstimatedTime());c8(a,d)}else j7("CP","No cast media video. Ignoring state update.")},f8=function(a,b,c){return(0,g.B)(function(a){this.tc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.tc("Retrying "+b+" using MDx browser channel."),e8(this,b,c))},a)},g8=function(a,b,c){g.KF.call(this);
this.D=window.NaN;this.P=!1;this.K=this.J=this.L=this.N=window.NaN;this.Y=[];this.C=this.G=this.B=this.ib=this.o=null;this.ua=a;this.Y.push(g.tF(window,"beforeunload",(0,g.B)(this.BL,this)));this.A=[];this.ib=new S7;this.ba=b.id;this.o=MEa(this,c);this.o.subscribe("handlerOpened",this.xS,this);this.o.subscribe("handlerClosed",this.uS,this);this.o.subscribe("handlerError",this.vS,this);this.o.subscribe("handlerMessage",this.wS,this);ZDa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.ib.videoId;g.XG()&&g.UG("yt-remote-session-video-id",a)},this)},h8=function(a){j7("conn",a)},MEa=function(a,b){return new d7(g7(a.ua,"/bc"),b)},i8=function(a,b){a.V("proxyStateChange",b)},NEa=function(a){a.D=g.aE((0,g.B)(function(){h8("Connecting timeout");
this.F(1)},a),2E4)},j8=function(a){g.cE(a.D);
a.D=window.NaN},k8=function(a){g.cE(a.N);
a.N=window.NaN},OEa=function(a){l8(a);
a.L=g.aE((0,g.B)(function(){m8(this,"getNowPlaying")},a),2E4)},l8=function(a){g.cE(a.L);
a.L=window.NaN},QEa=function(a,b){b&&(j8(a),k8(a));
b==(e7(a.o)&&(0,window.isNaN)(a.D))?b&&(i8(a,1),m8(a,"getSubtitlesTrack")):b?(a.aa()&&a.ib.reset(),i8(a,1),m8(a,"getNowPlaying"),PEa(a)):a.F(1)},REa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.ib.videoId&&(g.Yb(b.params)?a.ib.A=null:a.ib.A=b.params,a.V("remotePlayerChange"))},SEa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.ib.listId=b.params.listId||a.ib.listId;X7(a.ib,c,d);a.V("remoteQueueChange")},UEa=function(a,b){b.params=b.params||{};
SEa(a,b);TEa(a,b);a.V("autoplayDismissed")},TEa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
V7(a.ib,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.ib.o&&(c=-1E3);a.ib.o=c;c=Number(b.params.loadedTime);a.ib.K=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.ib.J=(0,window.isNaN)(c)?0:c;c=a.ib;var d=Number(b.params.liveIngestionTime);c.C=d;c.F=(0,window.isNaN)(d)?!1:!0;c=a.ib;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.D=(0,window.isNaN)(d)?0:d;c.B=(0,window.isNaN)(e)?0:e;1==a.ib.o?OEa(a):l8(a);
a.V("remotePlayerChange")},VEa=function(a,b){if(-1E3!=a.ib.o){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.ib.o=c;c=(0,window.parseInt)(b.params.currentTime,10);V7(a.ib,(0,window.isNaN)(c)?0:c);a.V("remotePlayerChange")}},WEa=function(a,b){var c="true"==b.params.muted;
a.ib.volume=(0,window.parseInt)(b.params.volume,10);a.ib.muted=c;a.V("remotePlayerChange")},XEa=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},YEa=function(a,b){var c="true"==b.params.hasNext;
a.ib.og="true"==b.params.hasPrevious;a.ib.hasNext=c;a.V("previousNextChange")},PEa=function(a){g.cE(a.K);
a.K=g.aE((0,g.B)(a.F,a,1),864E5)},m8=function(a,b,c){c?h8("Sending: action="+b+", params="+g.Gg(c)):h8("Sending: action="+b);
a.o.sendMessage(b,c)},n8=function(a){n7.call(this,"ScreenServiceProxy");
this.md=a;this.A=[];this.A.push(this.md.$_s("screenChange",(0,g.B)(this.sY,this)));this.A.push(this.md.$_s("onlineScreenChange",(0,g.B)(this.wU,this)))},cFa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.UD("MDX_CONFIG")||b;cDa();v6();o8||(o8=new f7(b?b.loungeApiHost:void 0),kDa()&&(o8.o="/api/loungedev"));p8||(p8=g.y("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",p8,void 0));ZEa();var c=q8();if(!c){var d=new w7(o8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=q8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);DEa(a,d,function(a){a?r8()&&R7(r8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.ZF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),s8("Initializing: "+g.Gg(b)),t8.push(g.VF("yt-remote-cast2-availability-change",function(){g.ZF("yt-remote-receiver-availability-change")})),t8.push(g.VF("yt-remote-cast2-receiver-selected",function(){u8(null);
g.ZF("yt-remote-auto-connect","cast-selector-receiver")})),t8.push(g.VF("yt-remote-cast2-receiver-resumed",function(){g.ZF("yt-remote-receiver-resumed","cast-selector-receiver")})),t8.push(g.VF("yt-remote-cast2-session-change",$Ea)),t8.push(g.VF("yt-remote-connection-change",function(a){a?R7(r8(),"YouTube TV"):v8()||(R7(null,null),GEa())})),a=w8(),b.isAuto&&(a.id+="#dial"),g.YD("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),s8(" -- with channel params: "+
g.Gg(a)),aFa(a),c.start(),r8()||bFa())},eFa=function(){var a=dFa();
O7()&&g.VG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},dFa=function(){var a=q8().md.$_gos();
var b=x8();b&&y8()&&(q6(a,b)||a.push(b));return bDa(a)},z8=function(){var a=fFa();
!a&&O7()&&FEa()&&(a={key:"cast-selector-receiver",name:FEa()});return a},fFa=function(){var a=dFa(),b=x8();
b||(b=v8());return g.Ia(a,function(a){return b&&m6(b,a.key)?!0:!1})},x8=function(){var a=r8();
if(!a)return null;var b=q8().Ge();return r6(b,a)},$Ea=function(a){s8("remote.onCastSessionChange_: "+n6(a));
if(a){var b=x8();b&&b.id==a.id?R7(b.id,"YouTube TV"):(b&&A8(),B8(a,1))}else y8()&&A8()},A8=function(){P7()?M7().stopSession():K7("stopSession called before API ready.");
var a=y8();a&&(a.disconnect(1),C8(null))},D8=function(){var a=y8();
return!!a&&3!=a.getProxyState()},s8=function(a){j7("remote",a)},q8=function(){if(!E8){var a=g.y("yt.mdx.remote.screenService_");
E8=a?new n8(a):null}return E8},r8=function(){return g.y("yt.mdx.remote.currentScreenId_")},gFa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},hFa=function(){return g.y("yt.mdx.remote.connectData_")},u8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},y8=function(){return g.y("yt.mdx.remote.connection_")},C8=function(a){var b=y8();
u8(null);a||gFa("");g.ua("yt.mdx.remote.connection_",a,void 0);p8&&((0,g.D)(p8,function(b){b(a)}),p8.length=0);
b&&!a?g.ZF("yt-remote-connection-change",!1):!b&&a&&g.ZF("yt-remote-connection-change",!0)},v8=function(){var a=g.XG();
if(!a)return null;var b=q8().Ge();return r6(b,a)},B8=function(a,b){x8()&&x8();
gFa(a.id);var c=new g8(o8,a,w8());c.connect(b,hFa());c.subscribe("beforeDisconnect",function(a){g.ZF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){y8()&&C8(null)});
C8(c)},bFa=function(){var a=v8();
a?(s8("Resume connection to: "+n6(a)),B8(a,0)):(w6(),GEa(),s8("Skipping connecting because no session screen found."))},ZEa=function(){var a=w8();
if(g.Yb(a)){a=u6();var b=g.VG("yt-remote-session-name")||"",c=g.VG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},w8=function(){return g.y("yt.mdx.remote.channelParams_")||{}},aFa=function(a){a?(g.UG("yt-remote-session-app",a.app),g.UG("yt-remote-session-name",a.name)):(g.WG("yt-remote-session-app"),g.WG("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},F8=function(a,b,c){g.M.call(this);
this.C=a;this.T=b;this.A=new g.HF(this);g.N(this,this.A);this.A.R(b,"onCaptionsTrackListChanged",this.OT);this.A.R(b,"captionschanged",this.rS);this.A.R(b,"captionssettingschanged",this.pG);this.A.R(b,"videoplayerreset",this.Eq);this.A.R(b,"mdxautoplaycancel",this.AK);this.P=this.A.R(b,"onVolumeChange",this.sE);this.G=!1;this.o=c;c.subscribe("proxyStateChange",this.HE,this);c.subscribe("remotePlayerChange",this.Jn,this);c.subscribe("remoteQueueChange",this.Eq,this);c.subscribe("autoplayUpNext",this.eE,
this);c.subscribe("previousNextChange",this.EE,this);c.subscribe("nowAutoplaying",this.vE,this);c.subscribe("autoplayDismissed",this.dE,this);this.suggestion=null;this.H=new g.LP(64);this.B=new g.V(this.lG,500,this);g.N(this,this.B);this.D=new g.V(this.mG,1E3,this);g.N(this,this.D);this.K=new E6(this.TX,0,this);g.N(this,this.K);this.F={};this.L=new g.V(this.LG,1E3,this);g.N(this,this.L);this.J=new g.ml(this.vQ,1E3,this);g.N(this,this.J);this.N=g.A;this.pG();this.Eq();this.Jn()},G8=function(a,b){var c=
a.C,d=a.T.getVideoData().lengthSeconds;
c.J=b||0;c.player.V("progresssync",b,d)},iFa=function(a){G8(a,0);
a.B.stop();H8(a,new g.LP(64))},J8=function(a,b){if(I8(a)&&!a.G){var c=null;
b&&(c={style:a.T.wj()},g.fc(c,b));a.o.aG(a.T.getVideoData(1).videoId,c);a.F=a8(a.o).A}},K8=function(a,b){var c=a.T.wg();
if(c){var d=c.Ee();var e=c.listId.toString()}var f=a.T.getVideoData(1);c=a.o;var k=f.videoId,l=d;d=f.playerParams;var m=f.Hk;f=SCa(f);var n=a8(c);l=l||0;var p={videoId:k,currentIndex:l};X7(n,k,l);g.u(b)&&(V7(n,b),p.currentTime=b);g.u(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.Gg(f));e8(c,"setPlaylist",p);e||c8(c,n);H8(a,new g.LP(1))},jFa=function(a,b){if(b){var c=a.T.Fc("captions","tracklist",{CB:1});
c&&c.length?(a.T.Yd("captions","track",b),a.G=!1):(a.T.Yk("captions"),a.G=!0)}else a.T.Yd("captions","track",{})},I8=function(a){return a8(a.o).videoId==a.T.getVideoData(1).videoId},H8=function(a,b){a.D.stop();
var c=a.H;if(!g.QP(c,b)){var d=g.X(b,2);d!=g.X(a.H,2)&&g.dU(a.T,d);a.H=b;kFa(a.C,c,b)}},L8=function(a){g.W.call(this,{I:"div",
M:"ytp-remote",O:[{I:"div",M:"ytp-remote-display-status",O:[{I:"div",M:"ytp-remote-display-status-icon",O:[g.Bqa()]},{I:"div",M:"ytp-remote-display-status-text",da:"{{statustext}}"}]}]});this.B=new g.aV(this,250);g.N(this,this.B);this.C=a;this.R(a,"presentingplayerstatechange",this.D);lFa(this,g.ZT(a))},lFa=function(a,b){if(3==a.C.Ta()){var c={RECEIVER_NAME:a.C.Fc("remote","currentReceiver").name};
c=g.X(b,128)?g.jX("Error on $RECEIVER_NAME",c):b.qb()||g.X(b,4)?g.jX("Playing on $RECEIVER_NAME",c):g.jX("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},M8=function(a,b){g.zY.call(this,"Play on",0,a,b);
this.T=a;this.H={};this.R(a,"onMdxReceiversChange",this.K);this.R(a,"presentingplayerstatechange",this.K);this.K()},N8=function(a){g.DU.call(this,a);
this.A={key:p6(),name:"This computer"};this.C=null;this.D=[];this.K=this.o=null;this.H=[this.A];this.B=this.A;this.F=new g.LP(64);this.J=0;this.G=-1;if(!g.OM(g.Y(this.player))){a=this.player;var b=g.NH(a);b&&(b=b.yn())&&(b=new M8(a,b),g.N(this,b));b=new L8(a);g.N(this,b);g.tU(a,b.element,4)}},kFa=function(a,b,c){a.F=c;
a.player.V("presentingplayerstatechange",new g.VP(c,b))},O8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)A8();
else{a.B=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.wg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.dc(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Hk,index:Math.max(a.player.IC(),0),currentTime:0==f?void 0:f};(d=SCa(d))&&(c.locationInfo=d);d=c}else d=null;s8("Connecting to: "+g.Gg(b));"cast-selector-receiver"==b.key?(u8(d||null),P7()?M7().setLaunchParams(d||
null):K7("setLaunchParams called before ready.")):!d&&D8()&&r8()==b.key?g.ZF("yt-remote-connection-change",!0):(A8(),u8(d||null),d=q8().Ge(),(d=r6(d,b.key))&&B8(d,1))}},ADa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},O6={"'":"\\'"},mFa={},YCa={HZ:"atp",r4:"ska",F3:"que",R2:"mus",n4:"sus",T0:"dsp"};
k6.prototype.So=function(){var a=new k6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var x6,t6="",B6=y6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",sDa=y6("loadCastFramework")||y6("loadCastApplicationFramework"),CEa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.C(E6,g.M);g.h=E6.prototype;g.h.wL=function(a){this.C=arguments;this.o=!1;this.Ea?this.B=(0,g.H)()+this.Cd:this.Ea=g.Bg(this.D,this.Cd)};
g.h.stop=function(){this.Ea&&(g.Cg(this.Ea),this.Ea=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.X=function(){this.stop();E6.ea.X.call(this)};
g.h.xL=function(){this.B?(this.Ea=g.Bg(this.D,this.B-(0,g.H)()),this.B=null):(this.Ea=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};F6.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
F6.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=G6.prototype;g.h.ej=null;g.h.Sf=!1;g.h.Ml=null;g.h.Lx=null;g.h.vl=null;g.h.yk=null;g.h.Sh=null;g.h.zi=null;g.h.Dj=null;g.h.Xc=null;g.h.Zn=0;g.h.Tf=null;g.h.Mr=null;g.h.Th=null;g.h.Mm=-1;g.h.HF=!0;g.h.Ri=!1;g.h.Zt=0;g.h.Sq=null;var yDa={},J6={};g.h=G6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.QW=function(a){a=a.target;var b=this.Sq;b&&3==g.ux(a)?b.Im():this.XG(a)};
g.h.XG=function(a){try{if(a==this.Xc)a:{var b=g.ux(this.Xc),c=this.Xc.A,d=this.Xc.getStatus();if(g.Hd&&!g.sc(10)||g.Jd&&!g.rc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.pf&&!g.yx(this.Xc))break a;this.Ri||4!=b||7==c||(8==c||0>=d?this.o.Lf(3):this.o.Lf(2));Q6(this);var e=this.Xc.getStatus();this.Mm=e;var f=g.yx(this.Xc);(this.Sf=200==e)?(4==b&&M6(this),this.D?(zDa(this,b,f),g.pf&&this.Sf&&3==b&&(this.Z.W(this.A,"tick",this.MW),this.A.start())):L6(this,f),this.Sf&&!this.Ri&&(4==b?this.o.Cq(this):
(this.Sf=!1,I6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Th=3,K6(13)):(this.Th=0,K6(14)),M6(this),N6(this))}}catch(k){this.Xc&&g.yx(this.Xc)}finally{}};
g.h.MW=function(){var a=g.ux(this.Xc),b=g.yx(this.Xc);this.Zn<b.length&&(Q6(this),zDa(this,a,b),this.Sf&&4!=a&&I6(this))};
g.h.YV=function(a){P6((0,g.B)(this.XV,this,a),0)};
g.h.XV=function(a){this.Ri||(Q6(this),L6(this,a),I6(this))};
g.h.QE=function(a){P6((0,g.B)(this.WV,this,a),0)};
g.h.WV=function(a){this.Ri||(M6(this),this.Sf=a,this.o.Cq(this),this.o.Lf(4))};
g.h.cancel=function(){this.Ri=!0;M6(this)};
g.h.oW=function(){this.Ml=null;var a=(0,g.H)();0<=a-this.Lx?(2!=this.yk&&this.o.Lf(3),M6(this),this.Th=2,K6(18),N6(this)):CDa(this,this.Lx-a)};g.h=FDa.prototype;g.h.Xt=null;g.h.Me=null;g.h.Tq=!1;g.h.UA=null;g.h.ip=null;g.h.Ru=null;g.h.Yt=null;g.h.ff=null;g.h.Yg=-1;g.h.Lm=null;g.h.Wl=null;g.h.connect=function(a){this.Yt=a;a=S6(this.o,null,this.Yt);K6(3);this.UA=(0,g.H)();var b=this.o.H;null!=b?(this.Lm=b[0],(this.Wl=b[1])?(this.ff=1,GDa(this)):(this.ff=2,U6(this))):(j6(a,"MODE","init"),this.Me=new G6(this,void 0,void 0,void 0),this.Me.ej=this.Xt,H6(this.Me,a,!1,null,!0),this.ff=0)};
g.h.BK=function(a){if(a)this.ff=2,U6(this);else{K6(4);var b=this.o;b.kg=b.Fh.Yg;a7(b,9)}a&&this.Lf(2)};
g.h.tt=function(a){return this.o.tt(a)};
g.h.abort=function(){this.Me&&(this.Me.cancel(),this.Me=null);this.Yg=-1};
g.h.TA=function(){return!1};
g.h.IE=function(a,b){this.Yg=a.Mm;if(0==this.ff)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.kg=this.Yg;a7(c,2);return}this.Lm=c[0];this.Wl=c[1]}else c=this.o,c.kg=this.Yg,a7(c,2);else if(2==this.ff)if(this.Tq)K6(7),this.Ru=(0,g.H)();else if("11111"==b){if(K6(6),this.Tq=!0,this.ip=(0,g.H)(),c=this.ip-this.UA,!g.Hd||g.sc(10)||500>c)this.Yg=200,this.Me.cancel(),K6(12),T6(this.o,this,!0)}else K6(8),this.ip=this.Ru=(0,g.H)(),this.Tq=!1};
g.h.Cq=function(){this.Yg=this.Me.Mm;if(this.Me.Sf)0==this.ff?this.Wl?(this.ff=1,GDa(this)):(this.ff=2,U6(this)):2==this.ff&&((!g.Hd||g.sc(10)?!this.Tq:200>this.Ru-this.ip)?(K6(11),T6(this.o,this,!1)):(K6(12),T6(this.o,this,!0)));else{0==this.ff?K6(9):2==this.ff&&K6(10);var a=this.o;a.kg=this.Yg;a7(a,2)}};
g.h.Sn=function(){return this.o.Sn()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Lf=function(a){this.o.Lf(a)};g.h=V6.prototype;g.h.tm=null;g.h.pe=null;g.h.Bc=null;g.h.Wt=null;g.h.mp=null;g.h.rz=null;g.h.Bp=null;g.h.En=0;g.h.KR=0;g.h.Bd=null;g.h.Kh=null;g.h.Kg=null;g.h.Ui=null;g.h.Fh=null;g.h.Kr=null;g.h.Ok=-1;g.h.RB=-1;g.h.kg=-1;g.h.mk=0;g.h.Zj=0;g.h.Ti=8;var b7=new g.Of;g.C(IDa,g.nf);g.C(JDa,g.nf);g.C(KDa,g.nf);g.h=V6.prototype;g.h.connect=function(a,b,c,d,e){K6(0);this.Wt=b;this.tm=c||{};d&&g.u(e)&&(this.tm.OSID=d,this.tm.OAID=e);this.F?(P6((0,g.B)(this.Nz,this,a),100),ODa(this)):this.Nz(a)};
g.h.Nz=function(a){this.Fh=new FDa(this);this.Fh.Xt=null;this.Fh.A=this.D;this.Fh.connect(a)};
g.h.TA=function(){return 0==this.o};
g.h.OE=function(a){this.Kh=null;RDa(this,a)};
g.h.NE=function(){this.Kg=null;this.Bc=new G6(this,this.B,"rpc",this.G);this.Bc.ej=null;this.Bc.Zt=0;var a=this.rz.clone();g.Rm(a,"RID","rpc");g.Rm(a,"SID",this.B);g.Rm(a,"CI",this.Kr?"0":"1");g.Rm(a,"AID",this.Ok);W6(this,a);if(!g.Hd||g.sc(10))g.Rm(a,"TYPE","xmlhttp"),H6(this.Bc,a,!0,this.Bp,!1);else{g.Rm(a,"TYPE","html");var b=this.Bc,c=!!this.Bp;b.yk=3;b.Sh=i6(a.clone());BDa(b,c)}};
g.h.IE=function(a,b){if(0!=this.o&&(this.Bc==a||this.pe==a))if(this.kg=a.Mm,this.pe==a&&3==this.o)if(7<this.Ti){try{var c=this.D.parse(b)}catch(f){c=null}if(g.xa(c)&&3==c.length)if(0==c[0])a:{if(!this.Kg){if(this.Bc)if(this.Bc.vl+3E3<this.pe.vl)Y6(this),this.Bc.cancel(),this.Bc=null;else break a;$6(this);K6(19)}}else this.RB=c[1],0<this.RB-this.Ok&&37500>c[2]&&this.Kr&&0==this.Zj&&!this.Ui&&(this.Ui=P6((0,g.B)(this.mS,this),6E3));else a7(this,11)}else b!=mFa.K_.o&&a7(this,11);else if(this.Bc==a&&
Y6(this),!g.F(b)){c=this.D.parse(b);g.xa(c);for(var d=0;d<c.length;d++){var e=c[d];this.Ok=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.Bp=e[2],e=e[3],null!=e?this.Ti=e:this.Ti=6,this.o=3,this.Bd&&this.Bd.Ez(),this.rz=S6(this,this.Sn()?this.Bp:null,this.Wt),SDa(this)):"stop"==e[0]&&a7(this,7):3==this.o&&("stop"==e[0]?a7(this,7):"noop"!=e[0]&&this.Bd&&this.Bd.Dz(e),this.Zj=0)}}};
g.h.mS=function(){null!=this.Ui&&(this.Ui=null,this.Bc.cancel(),this.Bc=null,$6(this),K6(20))};
g.h.Cq=function(a){if(this.Bc==a){Y6(this);this.Bc=null;var b=2}else if(this.pe==a)this.pe=null,b=1;else return;this.kg=a.Mm;if(0!=this.o)if(a.Sf)1==b?(b=(0,g.H)()-a.vl,b7.dispatchEvent(new JDa(b7,a.Dj?a.Dj.length:0,b,this.mk)),X6(this),this.C.length=0):SDa(this);else{var c=a.Th,d;if(!(d=3==c||7==c||0==c&&0<this.kg)){if(d=1==b)this.pe||this.Kh||1==this.o||2<=this.mk?d=!1:(this.Kh=P6((0,g.B)(this.OE,this,a),TDa(this,this.mk)),this.mk++,d=!0);d=!(d||2==b&&$6(this))}if(d)switch(c){case 1:a7(this,5);
break;case 4:a7(this,10);break;case 3:a7(this,6);break;case 7:a7(this,12);break;default:a7(this,2)}}};
g.h.YK=function(a){if(!g.Ma(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.EX=function(a){a?K6(2):(K6(1),UDa(this,8))};
g.h.tt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.ox;a.H=!1;return a};
g.h.isActive=function(){return!!this.Bd&&this.Bd.isActive(this)};
g.h.Lf=function(a){b7.dispatchEvent(new KDa(b7,a))};
g.h.Sn=function(){return!(!g.Hd||g.sc(10))};
g.h=VDa.prototype;g.h.Ez=function(){};
g.h.Dz=function(){};
g.h.Cz=function(){};
g.h.Us=function(){};
g.h.AA=function(){return{}};
g.h.isActive=function(){return!0};g.C(c7,g.M);g.h=c7.prototype;g.h.PV=function(){this.Cd=Math.min(3E5,2*this.Cd);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.Cd+15E3*Math.random();g.mu(this.o,a);this.A=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Cd=5E3};g.C(d7,VDa);g.h=d7.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.ee=function(a){return this.B.ee(a)};
g.h.V=function(a,b){return this.B.V.apply(this.B,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.kf(this.B),YDa(this),g.kf(this.A),this.A=null)};
g.h.la=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new V6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.N),e=this.o;e&&(e.Bd=null);d.Bd=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.Ok):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.fc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):e7(this)&&PDa(this.o,c)};
g.h.Ez=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)PDa(this.o,a[b])}this.V("handlerOpened")};
g.h.Cz=function(a){var b=2==a&&401==this.o.kg;4==a||b||this.A.start();this.V("handlerError",a)};
g.h.Us=function(a){if(!this.A.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.AA=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.fc(a,this.D);return a};
g.h.Dz=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),NDa(this.o)):this.V("handlerMessage",new WDa(a[0],a[1]))};
g.h.oY=function(){this.A.isActive();var a=this.o,b=0;a.Bc&&b++;a.pe&&b++;0!=b||this.connect(this.D,this.C)};f7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
f7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
f7.prototype.D=function(a){a(Error("request timed out"))};var fEa=(0,g.H)(),i7=null,l7=Array(50),k7=-1,m7=!1;g.C(n7,g.KF);n7.prototype.Ge=function(){return this.o};
n7.prototype.contains=function(a){return!!q6(this.o,a)};
n7.prototype.get=function(a){return a?r6(this.o,a):null};
n7.prototype.info=function(a){j7(this.G,a)};g.C(o7,g.KF);var nFa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=o7.prototype;g.h.start=function(){!this.o&&(0,window.isNaN)(this.Ea)&&this.cH()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);(0,window.isNaN)(this.Ea)||(g.cE(this.Ea),this.Ea=window.NaN)};
g.h.X=function(){this.stop();o7.ea.X.call(this)};
g.h.cH=function(){this.Ea=window.NaN;this.o=g.rE(g7(this.F,"/pairing/get_screen"),{method:"POST",Sb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.B)(this.qY,this),onError:(0,g.B)(this.pY,this),Gd:(0,g.B)(this.rY,this)})};
g.h.qY=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new l6(c))};
g.h.pY=function(a){this.o=null;a.status&&404==a.status?this.A>=nFa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=nFa[this.A],this.Ea=g.aE((0,g.B)(this.cH,this),a),this.A++):this.V("pairingFailed",Error("Server error "+a.status))};
g.h.rY=function(){this.o=null;this.V("pairingFailed",Error("Server not responding"))};g.C(q7,n7);g.h=q7.prototype;g.h.start=function(){p7(this)&&this.V("screenChange");!g.VG("yt-remote-lounge-token-expiration")&&jEa(this);g.cE(this.A);this.A=g.aE((0,g.B)(this.start,this),1E4)};
g.h.add=function(a,b){p7(this);gEa(this,a);r7(this,!1);this.V("screenChange");b(a);a.token||jEa(this)};
g.h.remove=function(a,b){var c=p7(this);iEa(this,a)&&(r7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.h.Er=function(a,b,c,d){var e=p7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,r7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.h.X=function(){g.cE(this.A);q7.ea.X.call(this)};
g.h.LL=function(a){p7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}r7(this,!b);b&&j7(this.G,"Missed "+b+" lounge tokens.")};
g.h.KL=function(a){j7(this.G,"Requesting lounge tokens failed: "+a)};g.C(t7,g.KF);g.h=t7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.VG("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.H)()-144E5<a?0:a)?v7(this):(this.C=(0,g.H)()+3E5,g.UG("yt-remote-fast-check-period",this.C),this.Pw())};
g.h.isEmpty=function(){return g.Yb(this.o)};
g.h.update=function(){s7("Updating availability on schedule.");var a=this.F(),b=g.Ib(this.o,function(b,d){return b&&!!r6(a,d)},this);
u7(this,b)};
g.h.X=function(){g.cE(this.B);this.B=window.NaN;this.A&&(this.A.abort(),this.A=null);t7.ea.X.call(this)};
g.h.Pw=function(){g.cE(this.B);this.B=window.NaN;this.A&&this.A.abort();var a=mEa(this);if(g.Nb(a)){var b=g7(this.D,"/pairing/get_screen_availability");this.A=h7(this.D,b,{lounge_token:g.Qb(a).join(",")},(0,g.B)(this.wV,this,a),(0,g.B)(this.vV,this))}else u7(this,{}),v7(this)};
g.h.wV=function(a,b){this.A=null;var c=g.Qb(mEa(this));if(g.eb(c,g.Qb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;u7(this,d);v7(this)}else this.tc("Changing Screen set during request."),this.Pw()};
g.h.vV=function(a){this.tc("Screen availability failed: "+a);this.A=null;v7(this)};
g.h.tc=function(a){j7("OnlineScreenService",a)};g.C(w7,n7);g.h=w7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.V("screenChange"),this.A.isEmpty()||this.V("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.Er=function(a,b,c,d){this.B.contains(a)?this.B.Er(a,b,c,d):(a="Updating name of unknown screen: "+a.name,j7(this.G,a),d(Error(a)))};
g.h.Ge=function(a){return a?this.o:g.Ua(this.o,(0,g.Ud)(this.C,function(a){return!this.contains(a)},this))};
g.h.dH=function(){return(0,g.Ud)(this.Ge(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.eH=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new o7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.B)(function(a){g.kf(f);d(x7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.kf(f);e(a)});
f.start();return(0,g.B)(f.stop,f)};
g.h.tY=function(a,b,c,d){g.rE(g7(this.F,"/pairing/get_screen"),{method:"POST",Sb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.B)(function(a,d){var e=new l6(d.screen||{});if(!e.name||qEa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);qEa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(x7(this,e))},this),
onError:(0,g.B)(function(a){d(Error("pairing request failed: "+a.status))},this),
Gd:(0,g.B)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.kf(this.B);g.kf(this.A);w7.ea.X.call(this)};
g.h.ZL=function(){rEa(this);this.V("screenChange");this.A.update()};
w7.prototype.dispose=w7.prototype.dispose;g.C(z7,g.KF);g.h=z7.prototype;g.h.Dq=function(a){this.B=a;this.V("sessionScreen",this.B)};
g.h.Le=function(a){this.la()||(a&&A7(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.h.info=function(a){j7(this.N,a)};
g.h.gH=function(){return null};
g.h.Vw=function(a){var b=this.A;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.B)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.B)(function(){A7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.Vw("");z7.ea.X.call(this)};g.C(B7,z7);g.h=B7.prototype;g.h.Uw=function(a){if(this.o){if(this.o==a)return;A7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);tEa(this)};
g.h.Qk=function(a){this.info("launchWithParams no-op for Cast: "+g.Gg(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.B)(function(){this.Le()},this),(0,g.B)(function(){this.Le(Error("Failed to stop receiver app."))},this)):this.Le(Error("Stopping cast device witout session."))};
g.h.Vw=g.A;g.h.X=function(){this.info("disposeInternal");g.cE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;B7.ea.X.call(this)};
g.h.AW=function(a,b){if(!this.la())if(b){var c=g.ix(b);if(g.Aa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Gg(c));switch(d){case "mdxSessionStatus":sEa(this,c.screenId);break;default:A7(this,"Unknown youtube message: "+d)}}else A7(this,"Unable to parse message.")}else A7(this,"No data in message.")};
g.h.JA=function(a,b,c,d){pEa(this.J,this.A.label,a,this.A.friendlyName,(0,g.B)(function(e){e?b(e):0<=d?(A7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.aE((0,g.B)(this.JA,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.gH=function(){return this.o};
g.h.uY=function(a){this.la()||a||(A7(this,"Cast session died."),this.Le())};g.C(C7,z7);g.h=C7.prototype;g.h.Uw=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.Qk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.A;g.cE(this.F);this.C?this.C.stop((0,g.B)(this.Le,this,null),(0,g.B)(this.Le,this,"Failed to stop DIAL device.")):this.Le()};
g.h.X=function(){this.o();this.o=g.A;g.cE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;C7.ea.X.call(this)};
g.h.xY=function(a){this.la()||a||(A7(this,"DIAL session died."),this.o(),this.o=g.A,this.Le())};
g.h.Du=function(a){this.K=p6();if(this.D){var b=new window.chrome.cast.DialLaunchResponse(!0,vEa(this));a(b);uEa(this)}else this.G=(0,g.B)(function(){g.cE(this.F);this.G=g.A;this.F=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,vEa(this));a(b);uEa(this)},this),this.F=g.aE((0,g.B)(function(){this.G()},this),100)};
g.h.nN=function(a,b,c){pEa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.B)(function(a){a&&a.token?(this.Dq(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Du(b,c)},this),(0,g.B)(function(a){A7(this,"Failed to get DIAL screen: "+a);
this.Du(b,c)},this))};g.C(D7,z7);D7.prototype.stop=function(){this.Le()};
D7.prototype.Uw=g.A;D7.prototype.Qk=function(){g.cE(this.o);this.o=window.NaN;var a=r6(this.J.Ge(),this.A.label);a?this.Dq(a):this.Le(Error("No such screen"))};
D7.prototype.X=function(){g.cE(this.o);this.o=window.NaN;D7.ea.X.call(this)};g.C(E7,g.KF);g.h=E7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.B)(this.KE,this),(0,g.B)(this.fV,this),d,e);c.customDialLaunchCallback=(0,g.B)(this.XS,this);window.chrome.cast.initialize(c,
(0,g.B)(function(){this.la()||(window.chrome.cast.addReceiverActionListener(this.C),cEa(),this.A.subscribe("onlineScreenChange",(0,g.B)(this.fH,this)),this.B=xEa(this),window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(a){this.tc("Failed to set initial custom receivers: "+g.Gg(a))},this)),this.V("yt-remote-cast2-availability-change",G7(this)),b(!0))},this),(0,g.B)(function(a){this.tc("Failed to initialize API: "+g.Gg(a));
b(!1)},this))};
g.h.mX=function(a,b){F7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)F7("Unsetting old screen status: "+this.o.A.friendlyName),H7(this,null)}if(a&&b){if(!this.o){c=r6(this.A.Ge(),a);if(!c){F7("setConnectedScreenStatus: Unknown screen.");return}var d=wEa(this,c);d||(F7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.B.push(d),
window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(a){this.tc("Failed to set initial custom receivers: "+g.Gg(a))},this)));
F7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);H7(this,new D7(this.A,d),!0)}this.o.Vw(b)}else F7("setConnectedScreenStatus: no screen.")};
g.h.nX=function(a){this.la()?this.tc("Setting connection data on disposed cast v2"):this.o?this.o.Qk(a):this.tc("Setting connection data without a session")};
g.h.wY=function(){this.la()?this.tc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),H7(this,null)):F7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.B)(this.KE,this),(0,g.B)(this.AV,this))};
g.h.X=function(){this.A.unsubscribe("onlineScreenChange",(0,g.B)(this.fH,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.C);g.Ra(g.y("yt.mdx.remote.debug.handlers_")||[],$Da);g.kf(this.o);E7.ea.X.call(this)};
g.h.tc=function(a){j7("Controller",a)};
g.h.LE=function(a,b){this.o==a&&(b||H7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.h.bV=function(a,b){if(!this.la())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),F7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)F7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{F7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.V("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:H7(this,
new D7(this.A,a));break;case window.chrome.cast.ReceiverType.DIAL:H7(this,new C7(this.A,a,this.F));break;case window.chrome.cast.ReceiverType.CAST:H7(this,new B7(this.A,a));break;default:this.tc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.tc("Stopping receiver w/o session: "+a.friendlyName)}else this.tc("onReceiverAction_ called without receiver.")};
g.h.XS=function(a){if(this.la())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.tc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.tc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.o.B)return F7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.o.B),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.tc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);H7(this,new C7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.B)(b.nN,b,(b.H.extraData||{}).screenId||null)):new window.Promise((0,g.B)(b.Du,b))};
g.h.KE=function(a){if(!this.la()){F7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)F7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),H7(this,new B7(this.A,b),!0);else{this.tc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=r6(this.A.Ge(),c.label);
d&&m6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(F7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.kf(this.o),this.o=new B7(this.A,b),this.o.subscribe("sessionScreen",(0,g.B)(this.LE,this,this.o)),this.o.Qk(null));this.o.Uw(a)}}};
g.h.vY=function(){return this.o?this.o.gH():null};
g.h.AV=function(a){this.la()||(this.tc("Failed to estabilish a session: "+g.Gg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&H7(this,null))};
g.h.fV=function(a){F7("Receiver availability updated: "+a);if(!this.la()){var b=G7(this);this.D=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;G7(this)!=b&&this.V("yt-remote-cast2-availability-change",G7(this))}};
g.h.fH=function(){this.la()||(this.B=xEa(this),F7("Updating custom receivers: "+g.Gg(this.B)),window.chrome.cast.setCustomReceivers(this.B,g.A,(0,g.B)(function(){this.tc("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",G7(this)))};
E7.prototype.setLaunchParams=E7.prototype.nX;E7.prototype.setConnectedScreenStatus=E7.prototype.mX;E7.prototype.stopSession=E7.prototype.wY;E7.prototype.getCastSession=E7.prototype.vY;E7.prototype.requestSession=E7.prototype.requestSession;E7.prototype.init=E7.prototype.init;E7.prototype.dispose=E7.prototype.dispose;var N7=[];g.h=S7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";T7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.o=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.A=a.trackData,this.og=a.hasPrevious,this.hasNext=a.hasNext,this.H=a.playerTime,this.G=a.playerTimeAt,this.D=a.seekableStart,this.B=a.seekableEnd,this.J=a.duration,this.K=a.loadedTime,this.C=a.liveIngestionTime,this.F=!(0,window.isNaN)(this.C))};
g.h.qb=function(){return 1==this.o};
g.h.isAdPlaying=function(){return 1081==this.o};
g.h.getDuration=function(){return this.F?this.J+U7(this):this.J};
g.h.clone=function(){return new S7(Y7(this))};g.C($7,g.KF);g.h=$7.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.A,f8(this,"play")):e8(this,"play"),d8(this,1,W7(a8(this))),this.V("remotePlayerChange")):b8(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.A,f8(this,"pause")):e8(this,"pause"),d8(this,2,W7(a8(this))),this.V("remotePlayerChange")):b8(this,this.pause)};
g.h.bH=function(a){if(1==this.o){if(this.A){var b=a8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.qb()||3==b.o?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.A,f8(this,"seekTo",{newTime:a}))}else e8(this,"seekTo",{newTime:a});d8(this,3,a);this.V("remotePlayerChange")}else b8(this,g.Da(this.bH,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.A,f8(this,"stopVideo")):e8(this,"stopVideo");var a=a8(this);a.index=-1;a.videoId="";T7(a);c8(this,a);this.V("remotePlayerChange")}else b8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=a8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.B)(function(){j7("CP","set receiver volume: "+d)},this),(0,g.B)(function(){this.tc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.B)(function(){j7("CP","set receiver muted: "+b)},this),(0,g.B)(function(){this.tc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);e8(this,"setVolume",e)}c.muted=b;c.volume=a;c8(this,c)}else b8(this,g.Da(this.setVolume,a,b))};
g.h.aG=function(a,b){if(1==this.o){var c=a8(this),d={videoId:a};b&&(c.A={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Gg(b.style),g.fc(d,c.A));e8(this,"setSubtitlesTrack",d);c8(this,c)}else b8(this,g.Da(this.aG,a,b))};
g.h.Rx=function(a,b){if(1==this.o){e8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Mb.id});var c=a8(this);c.audioTrackId=b.Mb.id;c8(this,c)}else b8(this,g.Da(this.Rx,a,b))};
g.h.aH=function(a,b){if(1==this.o){if(a&&b){var c=a8(this);X7(c,a,b);c8(this,c)}e8(this,"previous")}else b8(this,g.Da(this.aH,a,b))};
g.h.ZG=function(a,b){if(1==this.o){if(a&&b){var c=a8(this);X7(c,a,b);c8(this,c)}e8(this,"next")}else b8(this,g.Da(this.ZG,a,b))};
g.h.fA=function(){1==this.o?e8(this,"dismissAutoplay"):b8(this,this.fA)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.V("proxyStateChange",a,this.o)}$7.ea.dispose.call(this)};
g.h.X=function(){KEa(this);this.C=null;this.D.clear();Z7(this,null);$7.ea.X.call(this)};
g.h.Sx=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.BC(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.WU=function(a,b){this.V(a,b)};
g.h.tS=function(a){if(!a)this.Hn(null),Z7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=a8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)j7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,c8(this,b)}};
g.h.Hn=function(a){j7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),LEa(this),this.V("remotePlayerChange")};
g.h.sS=function(a){a?(LEa(this),this.V("remotePlayerChange")):this.Hn(null)};
g.h.FS=function(){var a=HEa();a&&Z7(this,a)};
g.h.tc=function(a){j7("CP",a)};g.C(g8,g.KF);g.h=g8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.u(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.u(k)&&(l.currentIndex=k);c&&(this.ib.listId=c);this.ib.videoId=d;this.ib.index=k||0;this.ib.state=3;V7(this.ib,m);this.C="UNSUPPORTED";h8("Connecting with setPlaylist and params: "+g.Gg(l));this.o.connect({method:"setPlaylist",
params:g.Gg(l)},a,fDa())}else h8("Connecting without params"),this.o.connect({},a,fDa());NEa(this)};
g.h.dispose=function(){this.la()||(this.V("beforeDispose"),i8(this,3));g8.ea.dispose.call(this)};
g.h.X=function(){j8(this);l8(this);k8(this);g.cE(this.J);this.J=window.NaN;g.cE(this.K);this.K=window.NaN;this.B=null;g.uF(this.Y);this.Y.length=0;this.o.dispose();g8.ea.X.call(this);this.C=this.G=this.A=this.ib=this.o=null};
g.h.BL=function(){this.F(2)};
g.h.xS=function(){h8("Channel opened");this.P&&(this.P=!1,k8(this),this.N=g.aE((0,g.B)(function(){h8("Timing out waiting for a screen.");this.F(1)},this),15E3));
jDa(XDa(this.o),this.ba)};
g.h.uS=function(){h8("Channel closed");(0,window.isNaN)(this.D)?w6(!0):w6();this.dispose()};
g.h.vS=function(a){w6();(0,window.isNaN)(this.H())?(h8("Channel error: "+a+" without reconnection"),this.dispose()):(this.P=!0,h8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),i8(this,2))};
g.h.wS=function(a){a.params?h8("Received: action="+a.action+", params="+g.Gg(a.params)):h8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.ix(a.params.devices);this.A=(0,g.I)(a,function(a){return new k6(a)});
a=!!g.Ia(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
QEa(this,a);break;case "loungeScreenDisconnected":g.Sa(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
QEa(this,!1);break;case "remoteConnected":var b=new k6(g.ix(a.params.device));g.Ia(this.A,function(a){return b?a.id==b.id:!1})||g.Pa(this.A,b);
break;case "remoteDisconnected":b=new k6(g.ix(a.params.device));g.Sa(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":SEa(this,a);break;case "nowPlaying":UEa(this,a);break;case "onStateChange":TEa(this,a);break;case "onAdStateChange":VEa(this,a);break;case "onVolumeChanged":WEa(this,a);break;case "onSubtitlesTrackChanged":REa(this,a);break;case "nowAutoplaying":XEa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.V("autoplayModeChange",this.C);"DISABLED"==this.C&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":YEa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:h8("Unrecognized action: "+a.action)}};
g.h.YW=function(){if(this.B){var a=this.B;this.B=null;this.ib.videoId!=a&&m8(this,"getNowPlaying")}};
g8.prototype.subscribe=g8.prototype.subscribe;g8.prototype.unsubscribeByKey=g8.prototype.ee;g8.prototype.ka=function(){var a=3;this.la()||(a=0,(0,window.isNaN)(this.H())?e7(this.o)&&(0,window.isNaN)(this.D)&&(a=1):a=2);return a};
g8.prototype.getProxyState=g8.prototype.ka;g8.prototype.F=function(a){h8("Disconnecting with "+a);j8(this);this.V("beforeDisconnect",a);1==a&&w6();YDa(this.o,a);this.dispose()};
g8.prototype.disconnect=g8.prototype.F;g8.prototype.ia=function(){var a=this.ib;this.B&&(a=this.ib.clone(),X7(a,this.B,a.index));return Y7(a)};
g8.prototype.getPlayerContextData=g8.prototype.ia;
g8.prototype.pa=function(a){var b=new S7(a);b.videoId&&b.videoId!=this.ib.videoId&&(this.B=b.videoId,g.cE(this.J),this.J=g.aE((0,g.B)(this.YW,this),5E3));var c=[];this.ib.listId==b.listId&&this.ib.videoId==b.videoId&&this.ib.index==b.index||c.push("remoteQueueChange");this.ib.o==b.o&&this.ib.volume==b.volume&&this.ib.muted==b.muted&&W7(this.ib)==W7(b)&&g.Gg(this.ib.A)==g.Gg(b.A)||c.push("remotePlayerChange");this.ib.reset(a);(0,g.D)(c,function(a){this.V(a)},this)};
g8.prototype.setPlayerContextData=g8.prototype.pa;g8.prototype.aa=function(){var a=this.o.F.id,b=g.Ia(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
g8.prototype.getOtherConnectedRemoteId=g8.prototype.aa;g8.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.H)():window.NaN};
g8.prototype.getReconnectTimeout=g8.prototype.H;g8.prototype.ca=function(){return this.C||"UNSUPPORTED"};
g8.prototype.getAutoplayMode=g8.prototype.ca;g8.prototype.ga=function(){return this.G||""};
g8.prototype.getAutoplayVideoId=g8.prototype.ga;g8.prototype.wa=function(){if(!(0,window.isNaN)(this.H())){var a=this.o.A;g.nu(a.o);a.start()}};
g8.prototype.reconnect=g8.prototype.wa;g8.prototype.ma=function(a,b){m8(this,a,b);PEa(this)};
g8.prototype.sendMessage=g8.prototype.ma;g.C(n8,n7);g.h=n8.prototype;g.h.Ge=function(a){return this.md.$_gs(a)};
g.h.contains=function(a){return!!this.md.$_c(a)};
g.h.get=function(a){return this.md.$_g(a)};
g.h.start=function(){this.md.$_st()};
g.h.add=function(a,b,c){this.md.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.md.$_r(a,b,c)};
g.h.Er=function(a,b,c,d){this.md.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.A.length;a<b;++a)this.md.$_ubk(this.A[a]);this.A.length=0;this.md=null;n8.ea.X.call(this)};
g.h.sY=function(){this.V("screenChange")};
g.h.wU=function(){this.V("onlineScreenChange")};
w7.prototype.$_st=w7.prototype.start;w7.prototype.$_gspc=w7.prototype.tY;w7.prototype.$_gsppc=w7.prototype.eH;w7.prototype.$_c=w7.prototype.contains;w7.prototype.$_g=w7.prototype.get;w7.prototype.$_a=w7.prototype.add;w7.prototype.$_un=w7.prototype.Er;w7.prototype.$_r=w7.prototype.remove;w7.prototype.$_gs=w7.prototype.Ge;w7.prototype.$_gos=w7.prototype.dH;w7.prototype.$_s=w7.prototype.subscribe;w7.prototype.$_ubk=w7.prototype.ee;var o8=null,p8=null,E8=null,t8=[];g.r(F8,g.M);g.h=F8.prototype;
g.h.X=function(){g.M.prototype.X.call(this);this.B.stop();this.D.stop();this.K.stop();this.N();this.o.unsubscribe("proxyStateChange",this.HE,this);this.o.unsubscribe("remotePlayerChange",this.Jn,this);this.o.unsubscribe("remoteQueueChange",this.Eq,this);this.o.unsubscribe("autoplayUpNext",this.eE,this);this.o.unsubscribe("previousNextChange",this.EE,this);this.o.unsubscribe("nowAutoplaying",this.vE,this);this.o.unsubscribe("autoplayDismissed",this.dE,this);this.o=this.C=null};
g.h.bD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(I8(this)){if(!a8(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":a8(this.o).qb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.J.Im(c[0],c[1]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":c=c[0],I8(this)&&this.o.Rx(this.T.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.T.getCurrentTime();K8(this,0==c?void 0:c);break;case "control_seek":K8(this,c[0]);break;case "control_subtitles_set_track":J8(this,c[0]);break;case "control_set_audio_track":c=c[0],I8(this)&&this.o.Rx(this.T.getVideoData(1).videoId,c)}};
g.h.rS=function(a){this.K.wL(a)};
g.h.TX=function(a){this.bD("control_subtitles_set_track",g.Yb(a)?null:a)};
g.h.pG=function(){var a=this.T.Fc("captions","track");g.Yb(a)||J8(this,a)};
g.h.sE=function(a){if(I8(this)){this.o.unsubscribe("remotePlayerChange",this.Jn,this);var b=Math.round(a.volume);a=!!a.muted;var c=a8(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.L.start();this.o.subscribe("remotePlayerChange",this.Jn,this)}};
g.h.OT=function(){g.Yb(this.F)||jFa(this,this.F);this.G=!1};
g.h.HE=function(a,b){this.D.stop();2==b&&this.mG()};
g.h.Jn=function(){if(I8(this)){this.B.stop();var a=a8(this.o);switch(a.o){case 1080:case 1081:case 1084:case 1085:this.C.G=1;break;case 1082:case 1083:this.C.G=0;break;default:this.C.G=-1}switch(a.o){case 1081:case 1:H8(this,new g.LP(8));this.lG();break;case 1085:case 3:H8(this,new g.LP(9));break;case 1083:case 0:H8(this,new g.LP(2));this.J.stop();G8(this,this.T.getVideoData().lengthSeconds);break;case 1084:H8(this,new g.LP(4));break;case 2:H8(this,new g.LP(4));G8(this,W7(a));break;case -1:H8(this,
new g.LP(64));break;case -1E3:H8(this,new g.LP(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=a8(this.o).A;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.F=a,jFa(this,a));a=a8(this.o);-1==a.volume||Math.round(this.T.getVolume())==a.volume&&this.T.isMuted()==a.muted||this.L.isActive()||this.LG()}else iFa(this)};
g.h.EE=function(){this.T.V("mdxpreviousnextchange")};
g.h.Eq=function(){I8(this)||iFa(this)};
g.h.AK=function(){this.o.fA()};
g.h.eE=function(a){a&&(a=g.rE("/watch_queue_ajax",{method:"GET",fd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.B)(this.bW,this)}))&&(this.N=(0,g.B)(a.abort,a))};
g.h.bW=function(a,b){var c=new g.AO(g.Y(this.T),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.T.V("mdxautoplayupnext",c)};
g.h.vE=function(a){(0,window.isNaN)(a)||this.T.V("mdxnowautoplaying",a)};
g.h.dE=function(){this.T.V("mdxautoplaycanceled")};
g.h.vQ=function(a,b){-1==a8(this.o).o?K8(this,a):b&&this.o.bH(a)};
g.h.LG=function(){if(I8(this)){var a=a8(this.o);this.A.Ha(this.P);a.muted?this.T.mute():this.T.xg();this.T.setVolume(a.volume);this.P=this.A.R(this.T,"onVolumeChange",this.sE)}};
g.h.lG=function(){this.B.stop();if(!this.o.la()){var a=a8(this.o);a.qb()&&H8(this,new g.LP(8));G8(this,W7(a));this.B.start()}};
g.h.mG=function(){this.D.stop();this.B.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!(0,window.isNaN)(a)&&this.D.start()};g.r(L8,g.W);L8.prototype.D=function(a){lFa(this,a.state)};g.r(M8,g.zY);M8.prototype.K=function(){var a=this.T.Fc("remote","receivers");a&&1<a.length&&!this.T.Fc("remote","quickCast")?(this.H=g.gb(a,this.D,this),g.AY(this,(0,g.I)(a,this.D)),a=this.T.Fc("remote","currentReceiver"),this.Kf(this.D(a)),this.enable(!0)):this.enable(!1)};
M8.prototype.D=function(a){return a.key};
M8.prototype.Jf=function(a){return"cast-selector-receiver"==a?"Cast...":this.H[a].name};
M8.prototype.Ed=function(a){g.zY.prototype.Ed.call(this,a);this.T.Yd("remote","currentReceiver",this.H[a]);this.C.Qb()};g.r(N8,g.DU);g.h=N8.prototype;g.h.create=function(){cFa(g.AM(g.Y(this.player)));this.D.push(g.VF("yt-remote-before-disconnect",this.nS,this));this.D.push(g.VF("yt-remote-connection-change",this.gV,this));this.D.push(g.VF("yt-remote-receiver-availability-change",this.FE,this));this.D.push(g.VF("yt-remote-auto-connect",this.eV,this));this.D.push(g.VF("yt-remote-receiver-resumed",this.dV,this));this.FE()};
g.h.load=function(){this.player.Bv();g.DU.prototype.load.call(this);this.C=new F8(this,this.player,this.o);var a=(a=hFa())?a.currentTime:0;var b=D8()?new $7(y8(),void 0):null;0==a&&b&&(a=W7(a8(b)));0!=a&&(this.J=a||0,this.player.V("progresssync",a,void 0));kFa(this,this.F,this.F);g.M_(this.player.app,6)};
g.h.unload=function(){this.player.V("mdxautoplaycanceled");this.B=this.A;g.mf(this.C,this.o);this.o=this.C=null;g.DU.prototype.unload.call(this);g.M_(this.player.app,5)};
g.h.X=function(){g.WF(this.D);g.DU.prototype.X.call(this)};
g.h.xn=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.bD.apply(this.C,[a].concat(g.oa(c)))};
g.h.rL=function(){return this.loaded?this.C.suggestion:null};
g.h.og=function(){return this.o?a8(this.o).og:!1};
g.h.hasNext=function(){return this.o?a8(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.jQ=function(){var a=a8(this.o),b=this.player.getVideoData();return{allowSeeking:g.Y(this.player).experiments.o("web_player_mdx_allow_seeking_change_killswitch")?this.player.Zc():!a.isAdPlaying()&&this.player.Zc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+U7(a):a.C,isPeggedToLive:1>=(a.F?a.B+U7(a):a.B)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.F?a.B+U7(a):a.B,seekableStart:0<a.D?a.D+U7(a):a.D}};
g.h.kQ=function(){this.o&&this.o.ZG()};
g.h.lQ=function(){this.o&&this.o.aH()};
g.h.nS=function(a){1==a&&(this.K=this.o?a8(this.o):null)};
g.h.gV=function(){var a=D8()?new $7(y8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.K=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.kf(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.player.getVideoData().videoId&&this.player.GC(a.videoId,W7(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.FE=function(){this.H=[this.A].concat(eFa());var a=z8()||this.A;O8(this,a);this.player.ya("onMdxReceiversChange")};
g.h.eV=function(){var a=z8();O8(this,a)};
g.h.dV=function(){this.B=z8()};
g.h.iQ=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?Q7():O8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&Q7(),!0):!1}};
g.h.mQ=function(){e8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Hc=function(){return!1};g.AX.remote=N8;})(_yt_player);
